- stubs/torch/nn/modules/__init__.pyi
> [fix] import TransformerEncoderLayer directly so pre-commit passes

- stubs/torch/__init__.pyi
- stubs/torch/utils/__init__.pyi
> Fix copyright in stubs

- .gitignore
- CONTRIBUTING.md
- [question] should we merge requirements-dev and requirements-test?
I am not sure the differences.
testing: ran the testing commands.
- [No ] Was this discussed/approved via a Github issue? (no need for typos, doc improvements)
- [ Yes] Did you read the [contributor guideline](https://github.com/facebookresearch/fairscale/blob/master/CONTRIBUTING.md)?
- [ Yes] Did you make sure to update the docs?
- [ N/A] Did you write any new necessary tests?
Fixes # (issue). N/A
Make sure you had fun coding 🙃 - sort of.
> [doc] added a bit details to initial setup

- .circleci/config.yml
- CONTRIBUTING.md
- README.md
- benchmarks/transformer.py
- fairscale/clib/fused_adam_cuda/compat.h
- fairscale/clib/fused_adam_cuda/fused_adam_cuda.cpp
- fairscale/clib/fused_adam_cuda/fused_adam_cuda_kernel.cu
- fairscale/clib/fused_adam_cuda/multi_tensor_apply.cuh
- fairscale/clib/fused_adam_cuda/type_shim.h
- fairscale/optim/adam.py
- setup.py
- tests/optim/test_adam.py
Adds FusedAdam cuda to Fairscale
> Add fused adam cuda

- fairscale/optim/oss.py
- fairscale/optim/utils.py
- tests/optim/test_oss.py
Fixes #8.
Follow up from another PR which got a bit messed up by originating from a fairscale fork
> Implement OSS save and load of the sharded state from a single replica

- fairscale/optim/oss.py
- fairscale/optim/utils.py
- tests/optim/test_oss.py
Fixes #8 
Yes mostly, I completely messed up the PR merge though, that was not fun but that's on me
> Restore PR #12

- CHANGELOG.md
- fairscale/__init__.py
- setup.py
> [chore] setup a proper version number

- .gitignore
- CHANGELOG.md
- MANIFEST.in
- fairscale/__init__.py
- pyproject.toml
> [fix] add build dependency on torch

- setup.py
> [cleanup] fix setup.py description

- .gitignore
- CONTRIBUTING.md
- requirements-test.txt
> add pytest coverage

- tests/optim/test_oss.py
> [fix] fix test_oss.py when host have 2 GPUs

- .circleci/config.yml
- .coveragerc
- .gitignore
> [chore] enable codecov

- benchmarks/transformer.py
- fairscale/clib/fused_adam_cuda/fused_adam_cuda_kernel.cu
- fairscale/optim/adam.py
- tests/optim/test_adam.py
Add option for fp16 optimizer state with Adam. Note that it likely won't converge on serious models
> Add fp16 optimizer state

- fairscale/optim/oss.py
- tests/optim/test_oss.py
> [fix] optim/oss: PyTorch already handles putting state on proper device

- fairscale/nn/data_parallel/oss_ddp.py
- tests/nn/data_parallel/test_oss_ddp.py
- added train(mode) method to be aware of eval mode
issue: close #27
> [fix] fix eval for oss_ddp

- CHANGELOG.md
- fairscale/__init__.py
> [chore] create v0.0.2

- docs/requirements.txt
Needed for working correctly with readthedocs.org
> [docs] add requirements.txt

- docs/requirements.txt
> [docs] specify sphinx version

- docs/requirements.txt
- docs/source/api/nn/pipe.rst
- docs/source/api/optim/oss.rst
- docs/source/conf.py
- docs/source/index.rst
> [docs] add docs for APIs

- docs/requirements.txt
> [docs] do not install pytorch_sphinx_theme as editable

- fairscale/optim/oss.py
> [fix] OSS async broadcast

- fairscale/optim/oss.py
- tests/optim/test_oss.py
> [feat] Gracefully handle local/global state dict queries

- .gitignore
Ease of life, remove typical intermediate files in the python world from the git tracking. Follows [the github default](https://github.com/github/gitignore/blob/master/Python.gitignore), and makes it possible to do something like `pytest --cov=fairscale.optim tests/optim/ --cov-report=term-missing` locally to run tests and check coverage without messing around the git status
Make sure you had fun coding 🙃 That was pretty fun indeed
> [chore] gitignore update

- README.md
- docs/source/tutorials/index.rst
- docs/source/tutorials/oss.rst
- fairscale/optim/oss.py
Adds a tutorial for OSS in the html docs. cf #63 
> [chore] OSS: add a small sphinx tutorial, similar to README

- README.md
> [docs] update installation instructions now that we have a pip package

- .circleci/config.yml
- benchmarks/oss.py
- fairscale/optim/oss.py
Fixes OSS being broken with the Gloo backend, rightfully so (in place operation on a tensor which requires_grad, undefined). Adds a CI test for Gloo so that we don't miss issues like this in the future
> Making oss gloo-compliant, check that it will stay the case

- docs/source/api/nn/pipe.rst
- docs/source/api/optim/oss.rst
- docs/source/conf.py
- fairscale/nn/pipe/batchnorm.py
- fairscale/nn/pipe/pipe.py
- fairscale/optim/oss.py
Improves on #63, should add a lot more documentation to [readthedocs](https://fairscale.readthedocs.io/en/latest/api). Remove all the warnings from sphinx, cross references should work
> [chore] Documentation fixes, no more ref issues and more API fields

- .circleci/config.yml
- benchmarks/oss.py
Making the benchmark code (includes OSS DDP) a bit easier on the eyes, refactored. Eventually needs to be added to the docs (cf. #63 and discussions). Also, make it completely deterministic, safer for future CI. It actually proves that the results of OSS are exactly the same as vanilla DDP, which is a good reference point to have
> [cleanup] Minor, OSS benchmark cleanup

- docs/source/tutorials/oss.rst
> edits oss.rst

- fairscale/optim/oss.py
> [fix] re-run black to fix CPU tests on master

- fairscale/nn/moe/top2gate.py
- tests/nn/moe/test_top2gating.py
> [fix] moe: fix Top2Gate to work on GPU

- fairscale/nn/moe/top2gate.py
> [refactor] moe: simplify logic removing top expert

- tests/nn/pipe/test_checkpoint_ddp.py
- this change adds test cases to reproduce the error with checkpoint & DDP
- mandeep mentioned that there is also deadlock in this case, but this
change doesn't cover that.
- we cover cases where weight sharing is OK
- however, same module multiple checkpoint or find_unused_parameters are
both not OK
> [test] Add unittest for checkpoint & DDP

- fairscale/optim/oss.py
> fix for megatron + oss

- fairscale/nn/__init__.py
- fairscale/nn/moe/__init__.py
- fairscale/nn/moe/moelayer.py
- tests/nn/moe/test_moelayer.py
Currently only implemented for a single process and expert.
> [feat] moe: initial implementation of MOELayer

- .circleci/config.yml
- fairscale/optim/oss.py
- tests/optim/test_oss.py
Catches the error in #127 in a more systematic basis
> [fix] OSS unit test to check data group

- docs/source/tutorials/oss.rst
The tutorial was wrong, in that nobody was doing the gradient reduction. Adding DDP so that we have a correct example here
> [minor] OSS doc fix - add the DDP wrap

- .circleci/config.yml
- benchmarks/oss.py
- docs/source/tutorials/oss.rst
Fixes a buggy training loop in both the tutorial and the benchmark, no need to all reduce the loss, that was a mistake
> [bugfix] OSS no reduce loss 

- benchmarks/oss.py
Useful in another branch and in general, add an option to the benchmark script to generate a chrome-tracing-compatible trace
Looks like (on a 2 gpu machine)
> [feat][minor] OSS: add a `--profile` benchmark option

- CHANGELOG.md
- fairscale/__init__.py
> [chore] create v0.0.3

- .circleci/config.yml
- fairscale/nn/moe/moelayer.py
- tests/nn/moe/test_moelayer.py
> [feat] moe: add all_to_all backward support

- fairscale/nn/moe/moelayer.py
- tests/nn/moe/test_moelayer.py
The expert annotation is used by clip_grads and DDP.
> [feat] moe: annotate expert params

- README.md
- docs/source/tutorials/adascale.rst
- docs/source/tutorials/index.rst
- fairscale/optim/__init__.py
- fairscale/optim/adascale.py
Add an implementation of AdaScale based on the AdaptDL project. The adascale.py file is re-licensed under BSD-3, as discussed in https://github.com/facebookresearch/fairscale/pull/111.
> Add implementation of AdaScale

- CONTRIBUTING.md
- fairscale/optim/__init__.py
- fairscale/optim/adascale.py
- ran black, isort, flake8, mypy
> [fix] fixing circleCI for AdaScale

- .circleci/config.yml
- benchmarks/oss.py
Make it possible to run the benchmark on cpu, just a handy change to simulate almost any process number irrespective to the number of gpus on the machine
> [feat][minor] OSS: benchmark - adding a cpu option

- fairscale/nn/data_parallel/sharded_ddp.py
Modified ShardedDDP to support multiple OSS optimizers as input, as we have a few cases in lightning where multiple optimizers are required! cc @blefaudeux 
> Support multiple optimizers in ShardedDDP

- README.md
- docs/source/tutorials/oss.rst
Fixes a not super relevant example for OSS in the Readme, overlooked (was without DDP and wrong)
> [docs][minor] fixing the readme example for oss

- fairscale/optim/__init__.py
- fairscale/optim/adascale.py
- stubs/torch/autograd/__init__.pyi
> [cleanup] mypy adascale

- stubs/torch/utils/checkpoint.pyi
- tests/nn/pipe/test_checkpoint_ddp.py
- fixed typing
- make it run less often to reduce CI time
testing: run it in a loop make sure it is run in the right frequency.
> [test] fine tune test for checkpoint & DDP

- fairscale/optim/oss.py
Just trying to make the code a little easier to read, and align with another branch (reducing the grads)
> [refactor][minor] OSS - small refactor of the bucketing

- benchmarks/oss.py
Helpful in debugging a bug that I have right now on another branch, and could be practical for some folks who want an easy way to benchmark OSS across typical vision workloads. It would be nice to add NLP workloads in there also, as a follow up
> [feat][minor] OSS benchmark - pick the model via args

- tests/nn/moe/test_moe_layer.py
> [test] moe: add a more thorough MOELayer routing test

- .circleci/config.yml
- benchmarks/oss.py
Fixes #158, uses a real case (classify numbers) to benchmark DDP vs. OSS/DDP vs. OSS/ShardedDDP 
> [feature] OSS: Use MNIST to benchmark

- .circleci/config.yml
> [bugfix] Hotfix perf requirements for OSS

- fairscale/nn/moe/moe_layer.py
- tests/nn/moe/test_moe_layer.py
> [feat] moe: add support for multiple experts per device

- .circleci/config.yml
- benchmarks/oss.py
- remove some noise from #157 
- add the --debug flag, which prints out more data, including some tensor descriptors
> [feat][minor] OSS Benchmark - add a debug option to add some tensor dumps

- .isort.cfg
- pyproject.toml
> [chore] consolidate tool's config

- .circleci/config.yml
- .pre-commit-config.yaml
- benchmarks/pipe.py
- pyproject.toml
- requirements-test.txt
- setup.cfg
- tests/optim/test_adam.py
> [chore] update isort to 5.6.4

- .circleci/config.yml
- README.md
- requirements-test.txt
- tests/nn/pipe/test_deferred_batch_norm.py
- tests/nn/pipe_process/test_pipe.py
> [chore] update to torch v1.7.0

- .circleci/config.yml
- README.md
- requirements-test.txt
- tests/nn/model_parallel/commons.py
> [chore] add circleci testing of torch==1.5.1

- docs/source/tutorials/adascale.rst
- fairscale/optim/adascale.py
> add warning to adascale before it is validated

- fairscale/optim/oss.py
> [feat] oss: add rank_local_state_dict staticmethod

- .circleci/config.yml
- benchmarks/oss.py
> [OSS][Minor] Add a torch AMP benchmark option and test job

- tests/optim/test_oss.py
Tentatively fixing issues that Tom and I were seeing on this unit test. All dist inits moved to a unique file, and one dist up at a time (used to be two with the module-wide dist init at the beginning of the file)
> [fix] OSS testing - remove concurrent dist inits

- fairscale/nn/moe/moe_layer.py
- fairscale/nn/moe/top2gate.py
- stubs/torch/__init__.pyi
- tests/nn/moe/test_moe_layer.py
- tests/nn/moe/test_top2gating.py
G dimension is implicit since we are already sharded.
> [refactor] moe: remove G dimension

- fairscale/nn/moe/moe_layer.py
- tests/nn/moe/test_moe_layer.py
> [fix] moe: fix bug for multiple experts per-gpu case

- fairscale/nn/moe/moe_layer.py
- fairscale/nn/moe/top2gate.py
> [refactor] moe: cleanup code to be more readable

- docs/source/api/index.rst
- docs/source/api/optim/adascale.rst
- docs/source/index.rst
- docs/source/tutorials/adascale.rst
- fairscale/optim/__init__.py
- fairscale/optim/adascale.py
- removed experimental warning as we have validated it on cifar and
imagenet, transformer is looking good so far too.
- fixed API doc formatting
- make it consistent with the other code in the repo
- tested by making the doc locally and inspect the results
> [doc] add AdaScale API doc

- benchmarks/pipe.py
- fairscale/nn/pipe/pipe.py
Add CPU support for benchmarks/pipe.py
> Add CPU support for pipe.py benchmarks

- benchmarks/pipe.py
- fairscale/nn/pipe/pipe.py
Fixes master, broke with #188 which let this change slip in
> [fix] Reverting a change which slipped in #188

- .circleci/config.yml
> [test] run moe mpi tests using torch_pg

- setup.py
> [fix] make extension build robust to include path

- .circleci/config.yml
- fairscale/utils/__init__.py
> [fix] make fairscale.utils a proper package

- .circleci/config.yml
- benchmarks/oss.py
Eventually fixes spurious regression testing.
- compute stats in a more robust way (classic, median and MAD instead of mean and std, same meaning)
- make sure that the kernels are done when taking a time stamp (if using cuda)
> [ShardedOptimizer] More robust stats for regression testing

- README.md
I realize that this is a prototype example, this PR makes it just slightly easier to follow by adding the missing import for `dist` and writing out `dist_init` as the reader may not know what is it supposed to be.
Thank you.
> [doc] make the basic example more "compilable"

- fairscale/optim/__init__.py
Fixes #205. It's strange that pytorch 1.5 worked on CI though, I'm wondering whether you were testing on a setup which did no have cuda @tchaton ? 
> [fix] Adding an import guard for amp with pytorch 1.6-

- docs/source/index.rst
> redirecting links to en?latest instead of local build folder

- .circleci/config.yml
Tentatively fixes flakiness of this test, could be due to the GPU not boosting to the same frequencies for instance (heat) or if these are not completely dedicated machines which have a noisy neighbour problem
> [fix] ad-hoc perf regression fix, more inconsistent than expected

- CHANGELOG.md
- fairscale/__init__.py
> [chore] create v0.1.0

- README.md
- docs/source/index.rst
- docs/source/tutorials/oss.rst
Some changes that we discussed with Vittorio, tentatively making it clearer what works with what, and adding ShardedDDP as an example. Super minor stuff
> [docs] Minor wording and structure changes / readthedocs

- CHANGELOG.md
- MANIFEST.in
- fairscale/__init__.py
> [fix] make sure pip package includes header files

- CHANGELOG.md
- README.md
- fairscale/optim/adascale.py
- tests/optim/test_adascale.py
- tests/optim/test_ddp_adascale.py
- tests/optim/test_single_node_adascale.py
> [feat] AdaScale: Gradient Accumulation and Add PyTest unit tests

- fairscale/nn/data_parallel/sharded_ddp.py
- fairscale/optim/oss.py
- fairscale/optim/utils.py
- fairscale/utils/testing.py
- tests/nn/data_parallel/test_sharded_ddp.py
Fixes #222. Overall I think that the bucketing is a little more elegant (the unroll of the bucket, be it after reduce or broadcast is factorized instead of being duplicated), the buckets store the destination and current rank once and for all so that callbacks are smaller, but I'm wondering whether tackling bucket-as-tensor-view directly would not be nicer. I'm also not sure of what to add as a unit test to catch this iGPT case, main idea is that some of the autograd hooks do not fire somehow (this is beyond ShardedDDP and a case that we need to handle anyway), so the buckets were not flushed in between the phases, open for suggestions.
If we didn't discuss your PR in Github issues there's a high chance it will …
> [fix] Fix iGPT buckets with ShardedDDP

- README.md
- docs/source/tutorials/oss.rst
> [fix] Sharded OSS/DDP hotfixes, bad documentation

- tests/optim/test_oss.py
> skipping some NCCL tests on 2-GPU systems

- fairscale/optim/grad_scaler.py
> [fix] Workaround Classy doing nasty things with optimizers

- fairscale/optim/oss.py
- tests/nn/data_parallel/test_sharded_ddp.py
…ssue that Sean spotted
Fixes #241.
- add a unit test to make sure that we don't break on that front in the future
- fix a gross counting error with respect to the number of requests which can be issued, which was the basis for a gatekeeper sync (which was then often wrong). Note that this is unrelated to the iGPT training problem a priori (unused parameter), which will still need to be properly tackled
cc @seannaren
> [fix] Check ShardedDDP / DDP parity + bugfix

- fairscale/nn/pipe/balance/__init__.py
- fairscale/nn/pipe/pipeline.py
- Added some notes as I was using those two functions.
- Also added a warning to pipeline.py when the partition output is not supported.
> [doc] updating the pipe balance doc a bit

- fairscale/nn/data_parallel/sharded_ddp.py
Minor, but cleaner code, there was an indirection level (enqueue a callback onto the _execution_engine) which was not needed (the callback calling it is in the right context already, said function can be inlined)
> [cleanup] ShardedDDP - no need to enqueue gatekeeper callback

- benchmarks/pipe.py
- examples/helpers.py
- examples/tutorial_oss.py
- examples/tutorial_pipe.py
- examples/tutorial_pipe_multiprocess.py
- examples/tutorial_pipe_rpc.py
- fairscale/nn/data_parallel/sharded_ddp.py
* adds CPU support to tutorials in examples --> works on machine without CUDA
* factorizes tutorials in examples to remove duplicate code
* fixes minor typos
> [feat] add CPU support to tutorials in examples + factorize tutorials

- fairscale/optim/oss.py
(master was not broken, this feature of skipping buckets for single node was "just" turned off). Reversing the commented code which slipped in 
> [fix] OSS - typo + small perf fix

- fairscale/optim/grad_scaler.py
Clould be involved in https://github.com/huggingface/transformers/issues/9156, and in general good to have: specify which process group should be used for the sharded grad scaler
> [feat] Specify process group for sharded grad scaler

- CHANGELOG.md
missed this item from previous AdaScale commits.
> [chore] Update changelog

- docs/source/api/optim/grad_scaler.rst
I just had a look at the doc given https://github.com/facebookresearch/fairscale/issues/270, and found that it was probably a bit confusing. This makes sure that ShardedGradScaler is shown within the OSS and ShardedDDP context
> [doc] improve on the ShardedGradScaler example

- tests/optim/test_oss.py
Discussed with @blefaudeux. 
This unit test covers distributed checkpointing with OSS (previous unit test only covers single rank). It checks that the following does not break the optimizer state:
- saving
- loading a saved checkpoint
It passes!
> Adds unit test for distributed checkpointing in OSS

- fairscale/utils/testing.py
- tests/nn/pipe_process/test_pipe.py
Minor, just fixing a case which was not caught on CI (where there are 4 gpus) but shows up locally: properly escape a test which requires 4 gpus and whose handling was broken by the recent file init change
> [hotfix] Catching properly a given test failing if not enough gpus

- CHANGELOG.md
- benchmarks/oss.py
- fairscale/optim/oss.py
Removes some dead code which was only useful for DDP, and must have some footprint for a big model (traverse the graph).
Opportunistically update the changelog, forgotten over many diffs
> [fix] Dead code removal for OSS

- fairscale/utils/testing.py
> [fix] Hopeful Circleci hangfix - teardown if raising exception

- fairscale/nn/data_parallel/sharded_ddp.py
- tests/nn/data_parallel/test_sharded_ddp.py
Fixes https://github.com/PyTorchLightning/pytorch-lightning/issues/5210 by ensuring that we pass in the correct ddp gpu count for the layer! I've added references to where I've taken the code from (cc @blefaudeux)
> [feat] Add Torch Sync Batchnorm handle in sharded DDP

- fairscale/nn/data_parallel/sharded_ddp.py
- tests/nn/data_parallel/test_sharded_ddp.py
Fixes broken master, following the landing of #265 with a typo.
> [fix] Typo in ShardedDDP unit test

- CHANGELOG.md
- fairscale/__init__.py
Bumps up the current fairscale version to 0.1.2 to include adascale improvements and huggingface-related fixes in ShardedDDP and OSS.
cc @stas00 
> [chore] create v0.1.2

- CHANGELOG.md
- fairscale/__init__.py
Fixes a version number issue, because number bump and release command interleaved for 0.1.2. This escalated quickly, but the right thing to do (^tm)
> [chore] creating 0.1.3 to align numbering everywhere

- CHANGELOG.md
- fairscale/__init__.py
- setup.py
> [fix] Adding missing CUDA files in the pip package v0.1.4

- fairscale/nn/data_parallel/sharded_ddp.py
- fairscale/optim/adascale.py
- fairscale/optim/oss.py
Following a couple of discussions (for instance in https://github.com/pytorch/pytorch/pull/46750), adding better explanations and suggestions directly in ShardedDDP docstrings
> [doc] ShardedDDP minor additions

- fairscale/optim/oss.py
- fairscale/optim/utils.py
Speedups by a couple of %, removes a lot of code, saves some memory (buckets are free)
> [perf][OSS] tensor views for bucketing

- fairscale/nn/data_parallel/sharded_ddp.py
- tests/nn/data_parallel/test_sharded_ddp.py
Expose the original module's attribute, can be a convenience
Reusing a code snippet I saw in @myleott's great branchs. Also present in Classy in multiple places, when I saw it it reminded me that we should support that here also
> [feat][ShardedDDP] Support the original module's attributes

- .circleci/config.yml
- README.md
> [chore] update to torch v1.7.1

- fairscale/optim/oss.py
- pyproject.toml
- tests/optim/test_oss.py
Fixes a broken case with the newish OSS support for tensor views. Buckets were resized to their actual use, to limit wasted memory, but their size was not updated when a new set of parameter was added (and to add insult to injury, the logic was based on the original bucket size..)
> [fix][OSS] Fix a broken case with tensor views + adding this to unit tests

- fairscale/nn/misc/flatten_params_wrapper.py
- fairscale/utils/testing.py
- tests/nn/misc/test_flatten_params_wrapper.py
Fixes a broken master. Unfortunately both overload and OrderedDict support is dependent on python versions and mostly broken, fixing that in the least disruptive way I believe (I did try other options)
> [fix] Lint flattenparams

- fairscale/nn/data_parallel/sharded_ddp.py
- fairscale/optim/oss.py
No logic change, but follow from the recent "tensor views" change, which removed the need for a callback after a transfer. In turn it means that for some async ops we only care about waiting for the last one, checking all the priors are just wasted cpu traffic. 
Added extra `torch.no_grad` whenever the operation is not part of the autograd graph anyway. The overhead is likely very small, but code wise it's not much either
Net result is a ~3-4% speed up (1380->1450 fps on my machine) on a small model, that would probably be a bit more for a very big one, not much but comes for free.
> [perf] ShardedDDP & OSS, small improvements

- fairscale/optim/oss.py
- pyproject.toml
Hopefully fixes https://github.com/PyTorchLightning/pytorch-lightning/issues/5646
The doc for this feature was not super clear, looks like even if the object is to be overwritten it should not be really empty.
No logic change, minor tweak, basically making sure that we don't rely on the broadcast_list() util to catch empty objects
cc @SeanNaren @robogast
> [OSS] Fix for torch dist broadcast randomly failing on dummy object

- fairscale/nn/pipe/pipe.py
> [fix] Fixing some docstrings which did not pass CI

- fairscale/nn/pipe/pipe.py
- fairscale/optim/oss.py
Unbeknownst to me this was broken in 1.7, fixed in 1.8 but not 1.7.1 (see https://github.com/pytorch/pytorch/pull/46897, the device is not respected). Thanks @SeanNaren for the heads up
May not be the only explanation, but definitely broken and part of https://github.com/PyTorchLightning/pytorch-lightning/issues/5646
> [fix] OSS: removing the torch broadcast util altogether, broken on 1.7.1

- tests/optim/test_oss.py
Typo, the world size was broken on CPU / no cuda available, not visible before somehow
> [fix] CPU OSS tests

- examples/tutorial_pipe_multiprocess.py
> [fix] examples: fix multiprocess pipe tutorial

- examples/helpers.py
- examples/tutorial_oss.py
- examples/tutorial_pipe.py
- examples/tutorial_pipe_multiprocess.py
- examples/tutorial_pipe_rpc.py
Fixes naming style of helper function examples. 
> [fix] examples: fix naming style of helper functions

- fairscale/nn/pipe/async_schedule.py
- fairscale/nn/pipe/multiprocess_pipe.py
- fairscale/nn/pipe/multiprocess_pipeline.py
> [cleanup] multiprocess_pipe: dead-code removal and simplification

- fairscale/utils/golden_testing_data.py
- fairscale/utils/testing_memory.py
- tests/optim/test_ddp_adascale.py
- tests/optim/test_oss_adascale.py
- tests/optim/test_single_node_adascale.py
> [test]: test adascale with oss

- benchmarks/experimental_ampnet.py
- benchmarks/pipe.py
- experimental/nn/ampnet_pipe/ampnet.py
- experimental/nn/ampnet_pipe/pipe.py
- experimental/tests/nn/ampnet_pipe_process/test_ampnet_pipe.py
- fairscale/nn/pipe/__init__.py
- fairscale/nn/pipe/async_pipe.py
- fairscale/nn/pipe/multiprocess_pipe.py
- fairscale/nn/pipe/rpc.py
- fairscale/nn/pipe/types.py
- tests/nn/model_parallel/test_layers.py
- tests/nn/pipe_process/skip/test_gpipe.py
- tests/nn/pipe_process/skip/test_leak.py
- tests/nn/pipe_process/test_bugs.py
- tests/nn/pipe_process/test_inplace.py
- tests/nn/pipe_process/test_pipe.py
- tests/nn/pipe_process/test_transparency.py
Will separate out the implementations in a follow-up PR.
> [refactor] make AsyncPipe its own class

- .circleci/config.yml
- .gitignore
- fairscale/optim/adascale.py
- fairscale/utils/testing.py
- requirements-benchmarks.txt
- requirements-dev.txt
- requirements-test.txt
- requirements.txt
- tests/optim/test_single_node_adascale.py
> [test]: test with py39 + torch 1.8 nightly

- fairscale/nn/pipe/async_pipe.py
- fairscale/nn/pipe/multiprocess_pipe.py
- fairscale/nn/pipe/multiprocess_pipeline.py
- tests/nn/pipe_process/test_pipe.py
> [refactor] pipe: move async-specific code out of MultiProcessPipe

- fairscale/nn/pipe/async_pipe.py
- fairscale/nn/pipe/async_pipeline.py
- fairscale/nn/pipe/multiprocess_pipe.py
- fairscale/nn/pipe/multiprocess_pipeline.py
- fairscale/nn/pipe/types.py
> [refactor] pipe: move async-specific code out of MultiProcessPipeline

- fairscale/nn/data_parallel/sharded_ddp.py
- tests/nn/data_parallel/test_sharded_ddp.py
Make sure that the buckets are moved when the base module changes devices. Add a corresponding unit test (which did break without this change)
> [fix] ShardedDDP - properly handle post device change

- fairscale/optim/__init__.py
- fairscale/optim/adascale.py
- tests/optim/test_oss_adascale.py
- This enables a different API for wrapping an optimizer with AdaScale.
- This also enables AdaScale to be wrapped by OSS.
- However, OSS wrapping AdaScale results in different optimization,
which future research will be needed to study its effects.
testing: add unit tests.
Fixes #302.
> [feat] Add AdaScaleWrapper

- CHANGELOG.md
- fairscale/__init__.py
> [chore] v0.1.5

- .circleci/config.yml
- benchmarks/golden_configs/oss_mnist.py
- benchmarks/oss.py
Fixes the regression not being run anymore, and adding a background test for the new multi-tensor optims (just checking that it runs and have an idea of the perf difference for now)
cc @izdeby
> [feat] OSS Benchmark - regression test + background testing new optims

- fairscale/nn/pipe/multiprocess_pipe.py
- tests/nn/pipe_process/test_pipe.py
> [refactor] multiprocess_pipe: cleanup __init__

- fairscale/nn/pipe/multiprocess_pipe.py
It is not currently being used so we can simplify the interface
by removing it.
> [refactor] multiprocess_pipe: remove retain_graph __init__ param

- tests/nn/data_parallel/test_sharded_ddp.py
> [feat] ShardedDDP : Adding a proper DDP parity / AMP unit test, overdue

- fairscale/nn/data_parallel/sharded_ddp.py
- unrolls a triple loop
- small memory savings in that the buckets are not allocated all upfront (which builds a bubble before the original params are released), but on the go (this happens once only, not for every step of course)
small low hanging fruits from https://github.com/huggingface/transformers/issues/8771#issuecomment-759248400, not planning to invest too much in that
> [perf] ShardedDDP - small memory use reduction - minor speedup

- fairscale/nn/pipe/async_pipe.py
- fairscale/nn/pipe/async_pipeline.py
- fairscale/nn/pipe/multiprocess_pipe.py
- fairscale/nn/pipe/rpc.py
> [refactor] AsyncPipe: do not sub-class MultiProcessPipe

- .github/workflows/build_wheels.yml
- CHANGELOG.md
- fairscale/__init__.py
Releases 0.1.6, many significant changes + a nasty bugfix which is nagging users  (https://github.com/SeanNaren/deepspeech.pytorch/issues/622)
> [chore] v0.1.6

- fairscale/optim/grad_scaler.py
Micro optim, probably does not change much in many cases, would have an impact if very cpu constrained and loads of ranks
> [minor] ShardGradScaler - only wait for the last handle

- benchmarks/offload.py
- fairscale/nn/__init__.py
- fairscale/nn/misc/__init__.py
- fairscale/nn/misc/offload.py
- tests/nn/misc/test_offload.py
This PR is for the offload feature. It has the following changes:
* Modify loop to remove the window technique. 
* Add support for activation offloading. This is only partial offloading. I am working on a more complete solution.
* Rename functions and remove comments that contain "rank"
* Add unit tests (just two for now but its a start)
> [offload] Add support for activation offloading + other changes

- fairscale/optim/oss.py
Reverts facebookresearch/fairscale#383
> Revert "[fix] oss dict load fix"

- fairscale/optim/oss.py
- tests/optim/test_oss.py
Fixes #380. Better take than #383 because fixing another issue which was not caught (383 was not enough), and reproducing the issue in an updated unit test so that this does not happen again. Thanks again @zhengwy888
> [fix] OSS dict load/save fix - better fix than 383 and unit test

- CHANGELOG.md
- fairscale/nn/data_parallel/sharded_ddp.py
- tests/nn/data_parallel/test_sharded_ddp.py
Fixes #388, make it possible to trigger a manual reduction (useful for checkpointing for instance).
cc @prigoyal 
> [feat][ShardedDDP] manual reduce option

- CHANGELOG.md
- fairscale/nn/data_parallel/sharded_ddp.py
- tests/nn/data_parallel/test_sharded_ddp.py
ShardedDDP was not respecting the eval() call from the base nn.Module class, at least not if the asserts were allowed
cc @vedanuj 
> [fix][minor] ShardedDDP train/eval modes

- fairscale/nn/data_parallel/sharded_ddp.py
- fairscale/utils/testing.py
- tests/nn/data_parallel/test_sharded_ddp.py
Needed for #351, and good practice in general
> [feat][ShardedDDP] Support multiple groups

- fairscale/nn/misc/__init__.py
> [fix] expose checkpoint_wrapper

- fairscale/optim/adascale.py
- tests/optim/test_single_node_adascale.py
> [bug]: fix a bug on custom smoothing factor

- docs/source/_templates/layout.html
- docs/source/_templates/theme_variables.jinja
- docs/source/api/index.rst
- docs/source/api/nn/misc/checkpoint_activations.rst
- docs/source/conf.py
- docs/source/index.rst
- fairscale/__init__.py
- fairscale/nn/misc/checkpoint_activations.py
- fairscale/optim/adascale.py
- setup.py
> [docs]: add checkpoint_wrapper and many small fixes

- CHANGELOG.md
- docs/source/api/index.rst
- docs/source/api/nn/fsdp.rst
- docs/source/index.rst
- fairscale/nn/__init__.py
- fairscale/nn/data_parallel/fully_sharded_data_parallel.py
> [docs] fsdp changelog and doc

- setup.py
This fixes `pip install -e .` for me and @sshleifer
> Add ninja to setup_requires

- fairscale/nn/data_parallel/sharded_ddp.py
> [hotfix] ShardedDDP - default fp16 flipped while testing, typo

- fairscale/nn/misc/checkpoint_activations.py
- tests/nn/misc/test_checkpoint_activations.py
> [test]: add peak mem in checkpoint test

- fairscale/nn/misc/checkpoint_activations.py
> [bug] use weakref in the wrapper

- fairscale/nn/data_parallel/fully_sharded_data_parallel.py
- tests/nn/data_parallel/test_fsdp.py
> [fix]: Fix non-float buffers in FSDP

- tests/nn/misc/test_checkpoint_activations.py
> [test] checkpoint: multiple input and output model test

- CHANGELOG.md
- fairscale/nn/data_parallel/sharded_ddp.py
- fairscale/utils/testing.py
- tests/nn/data_parallel/test_features_sharded_ddp.py
Makes it possible to use buckets with unused parameters, using the same technique as FSDP
> [ShardedDDP][Minor] Backport a bucket flush fix from FSDP, may help a few existing users

- fairscale/nn/data_parallel/fully_sharded_data_parallel.py
- fairscale/utils/containers.py
- fairscale/utils/testing.py
- tests/nn/data_parallel/test_fsdp_uneven.py
- tests/utils/test_containers.py
> [feat]: add summon_full_params context mgr

- .circleci/config.yml
> [chore] parallelize tests on GPUs

- fairscale/nn/data_parallel/fully_sharded_data_parallel.py
- fairscale/utils/testing.py
- tests/nn/data_parallel/test_fsdp.py
Similar to #434 but for FSDP now
> [fix] fix FSDP state_dict/load_state_dict for nested wrapped instances

- fairscale/nn/data_parallel/__init__.py
- fairscale/nn/data_parallel/fully_sharded_data_parallel.py
- tests/nn/data_parallel/test_fsdp.py
> [fix] FSDP: fix the corner case of all params are in the children

- fairscale/nn/model_parallel/initialize.py
> fixed typo

- tests/nn/data_parallel/test_fsdp_grad_scaler.py
first step for # (issue). Thanks @SeanNaren for contributing the test!
> [test] FSDP: add the failing test for #421

- fairscale/nn/pipe/async_schedule.py
- fairscale/nn/pipe/multiprocess_pipe.py
- fairscale/nn/pipe/multiprocess_pipeline.py
> [refactor] multiprocess_pipe: avoid unnecessary use of create_task and other cleanup

- README.md
- tests/nn/data_parallel/test_fsdp.py
- tests/nn/data_parallel/test_fsdp_uneven.py
> [docs] minor doc update

- benchmarks/experimental/experimental_ampnet.py
- benchmarks/pipe.py
- tests/nn/model_parallel/test_layers.py
- tests/nn/pipe/conftest.py
- tests/nn/pipe_process/conftest.py
- [X ] Did you read the [contributor guideline](https://github.com/facebookresearch/fairscale/blob/master/CONTRIBUTING.md)?
- Removes print logging since we should ideally be using the logging library.
- Removes unused functions in benchmarks/pipe.py
- Removes formatting print statements without args in other files.
> [refactor] Use logging in place of print statements, remove unused functions and other minor refactoring changes.

- .circleci/config.yml
- benchmarks/datasets/mnist.py
- benchmarks/oss.py
> [fix] Cache MNIST fetchs, use alternative URLs

- tests/experimental/nn/ampnet_pipe_process/test_ampnet_pipe.py
> Fix ampnet unit tests

- .circleci/config.yml
- setup.py
> [fix]: CI and check_version

- .circleci/config.yml
Slightly inelegant, but should help with CI flakyness in the short term
> [chore] CI retry apt-get install

- benchmarks/golden_configs/oss_mnist.py
- benchmarks/oss.py
Since the test is run in a single node, change the settings to reflect that (no reduce buckets), which bumps up the speed slightly (match a recent regression when enabling Variable.queue callback).
Better take than https://github.com/facebookresearch/fairscale/pull/480
> [chore] super minor, adjust OSS perf test case

- fairscale/nn/data_parallel/fully_sharded_data_parallel.py
The main change is making the GPU -> CPU grad transfer blocking. This is suboptimal from a performance perspective, but seems to be necessary to produce correct results when using CPU offloading on a single GPU.
I have not been able to reproduce this issue in a unit test (will circle back on this), but for now this should be a safe change since it primarily affects training speed.
> [fix] FSDP: fix CPU offload corner case

- fairscale/optim/oss.py
- tests/optim/test_oss.py
> [fix] OSS dict: simplified logic, bugfix for interleaved param groups 

- fairscale/nn/data_parallel/fully_sharded_data_parallel.py
- tests/nn/data_parallel/test_fsdp_no_sync.py
The previous fix was still slow for nested FSDP instances with reshard_after_forward=False
> [perf] Further improve performance for FSDP.no_sync

- .gitignore
- CHANGELOG.md
- RELEASE.md
- docs/source/conf.py
- fairscale/__init__.py
- mainly because vissl needs the new version
- added a doc on release steps
> [chore] 0.3.1 release

- benchmarks/pipe.py
- Fixes synthetic data function signature
- Removes unused flags since there is a chance that users will use it and run into [errors](https://github.com/facebookresearch/fairscale/pull/469).
> [refactor] Fix for using synthetic data + remove unused flags

- fairscale/nn/data_parallel/sharded_ddp.py
- fairscale/optim/oss.py
Seems to fix https://github.com/facebookresearch/fairscale/issues/498 (see [CI](https://app.circleci.com/pipelines/github/facebookresearch/fairscale?branch=gloo_check_all_handles), I kicked the jobs a couple of times in a row, all green). This is a change which is only needed for Gloo actually, but testing with several backends has other advantages so my take is that it's worth the very small perf hit
> [fix] flaky SDP tests with Gloo, checking all handles

- docs/source/tutorials/oss.rst
Fixes #477, states clearly that any way the user likes to spawn processes is completely fine.
cc @jesus-villalba
> [docs][minor] OSS/SDP - clarifying a confusing line in the docs #477

- benchmarks/benchmark_dataset.py
- benchmarks/experimental/benchmark_dataset.py
- benchmarks/experimental/experimental_ampnet.py
Adds support for training models using spectrain based asynchronous pipelining. Reference: https://arxiv.org/pdf/1809.02839.pdf
> [feat] experimental: Add spectrain support

- fairscale/optim/oss.py
> [fix] OSS/Lightning compatibility

- CHANGELOG.md
- fairscale/nn/data_parallel/fully_sharded_data_parallel.py
- tests/ci_test_list_3.txt
- tests/nn/data_parallel/test_fsdp_multiple_forward.py
> [fix] FSDP: multi-pass autograd graph and mixed precision

- fairscale/optim/oss.py
- tests/optim/test_oss.py
Makes it possible to fix https://github.com/PyTorchLightning/pytorch-lightning/issues/6387
> [feat] Make OSS state available on all ranks

- fairscale/optim/oss.py
- tests/optim/test_oss.py
Fixes #522, and adds a corresponding unit test 
> [feature][OSS] handle the device being changed after the fact

- fairscale/nn/data_parallel/fully_sharded_data_parallel.py
small refactor to make backward debugging easier in the future.
> [refactor] better backward debugging

- benchmarks/datasets/wikitext2_data.py
- benchmarks/experimental/offload.py
- benchmarks/golden_configs/lm_wikitext2.py
- benchmarks/pipe.py
- fairscale/experimental/nn/offload.py
This PR does the following:
- Removes the need to set requires_grad on all inputs(beginning and intermediate) and is the better long term solution whereby we use a dummy tensor to trigger the BW pass. (Thanks to Alban for helping with this tricky issue.)
- Perf improvement changes such as using multiple streams, pinning model shard memory and removing certain copies that allows overlap of copies. More changes coming soon.
> [offload] Add support for multiple streams and fix issue with integer inputs.

- fairscale/nn/data_parallel/sharded_ddp.py
Fixes https://github.com/facebookresearch/fairscale/issues/525
Removes code which was not used anymore
Remove changes from https://github.com/facebookresearch/fairscale/pull/528 to make it easier to grasp
> [cleanup][SDP] Removing dead or faulty code

- CHANGELOG.md
- fairscale/nn/data_parallel/fully_sharded_data_parallel.py
- fairscale/utils/parallel.py
- tests/ci_test_list_3.txt
- tests/nn/data_parallel/test_fsdp_regnet.py
- not fully validated yet but at least not asserting
- this enables VISSL to move forward with its next PR
> [feature] FSDP: enable pytorch SyncBN

- tests/optim/test_oss.py
Fixes part of #516. The tests were wrong in that the cuda device was not specified, that's why it hanged
> [fix][OSS] enabling disabled tests for 1.8

- CHANGELOG.md
- docs/source/conf.py
- fairscale/__init__.py
> [chore] 0.3.2 release

- benchmarks/golden_configs/oss_mnist.py
Should have been part of https://github.com/facebookresearch/fairscale/pull/532, tighten the memory requirements for the benchmark to make sure that the memory leak does not come back somehow
> [fix] Super minor, but make sure that the mem leak does not come back

- fairscale/utils/testing.py
- tests/experimental/nn/ampnet_pipe_process/test_ampnet_pipe.py
- tests/experimental/nn/test_multiprocess_pipe.py
- tests/nn/pipe_process/test_pipe.py
> [test] use workaround to enable rpc tests when cuda not available

- tests/nn/data_parallel/test_sharded_ddp_pytorch_parity.py
Checks that #517 does not come back (check that the grad norms are the same in between DDP and ShardedDDP for instance)
Removes changes from #528 
> [ci][SDP] Extending the test matrix which checks for equivalence with DDP

- docs/source/api/nn/sharded_ddp.rst
- docs/source/tutorials/oss.rst
- Explaining a little better that in the OSS+DDP case Torch AMP can be used as is
- Adding some "performance tips" to explain some of the ShardedDDP settings
> [SDP] Adding some more documentation

- CONTRIBUTING.md
- fairscale/__init__.py
- fairscale/experimental/__init__.py
- fairscale/experimental/nn/__init__.py
- fairscale/experimental/nn/ampnet_pipe/__init__.py
- fairscale/nn/__init__.py
- fairscale/nn/data_parallel/__init__.py
- fairscale/nn/misc/__init__.py
- fairscale/nn/model_parallel/__init__.py
- fairscale/nn/moe/__init__.py
- fairscale/nn/wrap/__init__.py
- fairscale/optim/__init__.py
- fairscale/utils/__init__.py
- fixes #471
- one less thing to worry about during development.
> [cleanup] consistent __init__.py for import *

- .circleci/config.yml
- README.md
> [chore] update to torch v1.8.1

- .circleci/config.yml
- tests/nn/data_parallel/test_sharded_ddp_pytorch_parity.py
> [chore] add testing of torch 1.9.0 nightly build

- benchmarks/experimental/offload.py
- fairscale/experimental/nn/offload.py
- tests/experimental/nn/test_offload.py
This PR is part of the audit for finalizing the OffloadModel API.
- Moves functions to being private
- Removes a redundant code path through the ShardSyncLayer
- other smaller nits/error messages.
> [offload] Audit OffloadModel API, add error messages and remove redundant code path.

- fairscale/experimental/nn/multiprocess_pipe.py
- tests/experimental/nn/test_multiprocess_pipe.py
> [refactor] multiprocess_pipe: only support torch >= 1.9.0

- benchmarks/experimental/experimental_async_approaches.py
- fairscale/experimental/nn/ampnet_pipe/ampnet.py
- fairscale/experimental/nn/ampnet_pipe/pipe.py
Add xpipe support for async model training. See https://arxiv.org/abs/1911.04610
> [feat] experimental: Add xpipe support

- docs/source/api/index.rst
> [fix] Remove folder that has not been added yet

- CHANGELOG.md
- docs/source/conf.py
- fairscale/__init__.py
- releasing 0.3.3
- I need it in vissl for the auto_wrap_bn change
> [chore] 0.3.3 release

- .circleci/config.yml
- requirements-test.txt
- tests/nn/moe/test_moe_layer.py
NCCL all_to_all is now supported in PyTorch (since v1.8.0)
Fixes: #548
> [test] modify MOE tests to use NCCL

- tests/nn/pipe_process/test_rpc.py
This test is flaky for torch >= 1.8.0.
> [test] disable test which has started to become flaky

- benchmarks/datasets/mnist.py
- fairscale/optim/oss.py
Fixes a change in torchvision, MNIST data is handled through mirrors now
> [CI] MNIST download fix

- fairscale/nn/data_parallel/sharded_ddp.py
- fairscale/optim/oss.py
- fairscale/optim/utils.py
- tests/optim/test_oss.py
Only keeps public what's reasonably necessary
> [OSS/ShardedDDP] making APIs more private

- fairscale/nn/data_parallel/sharded_ddp.py
- fairscale/optim/oss.py
- tests/nn/data_parallel/test_sharded_ddp_features.py
- tests/optim/test_oss.py
- [~x] Did you write any new necessary tests?
Fixes https://fb.workplace.com/groups/pytorchLightning/permalink/826203544631599/. I tried for some time but could not find a case in the unit test which would trigger this (inc. with pytorch 1.9 nightly), I've asked the users for repro examples and will update if something comes
Fixes another bug pre-emptively (no report yet), where the buckets could be of the wrong type if these were mixed and bad luck. Adds a unit test for this one
cc @ananthsub
> [fix][OSS] Mixed types & proper buckets + no grad_fn is fine

- fairscale/nn/pipe/pipe.py
> [cleanup] nn.Pipe: deprecate Pipe when torch version >= 1.8.0

- tests/nn/data_parallel/test_sharded_ddp_pytorch_parity.py
> [SDP] Adding a unit test which checks for multiple FW passes on the same block

- CHANGELOG.md
- docs/source/conf.py
- fairscale/__init__.py
> [chore] v0.3.4

- CHANGELOG.md
- docs/source/conf.py
- fairscale/__init__.py
> [chore] 0.3.5 release

- fairscale/nn/data_parallel/fully_sharded_data_parallel.py
Changing FSDP init to by pass pg validation for newly created process groups inside of init.
It speeds up FSDP init substantially.
> Changing FSDP init to by pass pg validation 

- fairscale/nn/data_parallel/fully_sharded_data_parallel.py
Fixing logging, changing info to debug to avoid clutter
> Fixing logging, changing info to debug to avoid clutter

- fairscale/nn/data_parallel/fully_sharded_data_parallel.py
- tests/nn/data_parallel/test_fsdp_input.py
- tests/nn/data_parallel/test_fsdp_regnet.py
- CI didn't seem to catch this or maybe I merged incorrectly yesterday
- this should fix the mypy error on master
- also updated a test that seems to be flaky due to tcp port conflict
> [fix] mypy and flaky test

- CHANGELOG.md
- docs/source/conf.py
- fairscale/__init__.py
- setup.py
> [chore] 0.3.6 release

- .github/PULL_REQUEST_TEMPLATE.md
(not visible here) add a suggestion in the PR template that people should update the Changelog, so that releases get a lot easier (will still be true if they get more automated)
> [chore] Suggest a changelog addition for each PR

- fairscale/nn/data_parallel/sharded_ddp.py
Adding a couple of labels on the shardedDDP side
> [chore] SDP - adding the profiler labels

- fairscale/optim/oss.py
Adds labels to the different steps within OSS
> [chore] Adding some profiling labels to OSS

- CHANGELOG.md
- pyproject.toml
- setup.py
> [chore] do not build cuda extensions by default

- fairscale/experimental/nn/distributed_pipeline/graph.py
- fairscale/experimental/nn/distributed_pipeline/trace.py
- setup.cfg
- tests/experimental/nn/test_multiprocess_pipe.py
* Simplified PipelineModulesGraph API
*  Added make_graph utility that uses torch.fx to generate PipelineModulesGraph for a module automatically.
> adding auto graph generation for distributed pipeline

- tests/nn/data_parallel/test_fsdp_regnet.py
- Added sync_bn on/off cases
- Added conv and linear bias on/off cases
- clarified when sync_bn is off, when is BN wrapping needed with the test
> [test] improve BN test coverage

- .pre-commit-config.yaml
- fairscale/nn/data_parallel/sharded_ddp.py
- fairscale/optim/utils.py
- tests/nn/data_parallel/test_sharded_ddp_features.py
Improves the coverage on SDP, still missing a few lines but better kept for another PR
> [test][minor] Improving SDP test coverage

- tests/nn/data_parallel/test_sharded_ddp_features.py
- tests/nn/data_parallel/test_sharded_ddp_pytorch_parity.py
Quick follow up from https://github.com/facebookresearch/fairscale/pull/639#discussion_r623327584, using the nice util from @min-xu-ai  to automatically clean up the mess
> [refactor][minor][sdp] using context-based tempfiles

- tests/ci_test_list_1.txt
- tests/nn/pipe/test_parity.py
> [test] nn.Pipe: add a parity test that also tests with amp

- fairscale/utils/testing.py
This is very minor and testing only change.
> [minor] not creating a temp file on import

- CHANGELOG.md
- fairscale/nn/data_parallel/sharded_ddp.py
- tests/nn/data_parallel/test_sharded_ddp_features.py
Fixes https://github.com/facebookresearch/fairscale/issues/646 and makes sure that this does not happen again. Sorry @apsdehal
> [fix] SDP: expose module property fix + unit test

- .pre-commit-config.yaml
- fairscale/experimental/__init__.py
- fairscale/experimental/optim/__init__.py
- fairscale/experimental/optim/dynamic_loss_scaler.py
- tests/ci_test_list_2.txt
- tests/experimental/optim/test_dynamic_loss_scaler.py
Added dynamic loss scaler to avoid gradient overflow/underflow by scaling the loss.
The DynamicLossScaler can be used in the same manner with GradScaler except that it can be applied to cup devices. https://pytorch.org/docs/stable/notes/amp_examples.html#amp-examples
cc @blefaudeux @msbaines Please feel free to review the code.
> [feat]Adding DynamicLossScaler class for supporting optimizer updates on the CPU

- CONTRIBUTING.md
* Specify PEP8 as the style guide that FairScale contributors should use.
> [chore] Specify the style guide in our Contributing doc

- fairscale/nn/data_parallel/sharded_ddp.py
- tests/nn/data_parallel/test_sharded_ddp_features.py
Increasing the code coverage, good practice and actually raised small, not signalled bugs
> [draft][chore] SDP : increase code coverage

- fairscale/optim/adascale.py
Fixed infinite loop in docstring with other minor changes.
> [fix][adascale] Fix infinite loop in docstring

- CHANGELOG.md
- fairscale/nn/data_parallel/fully_sharded_data_parallel.py
- tests/nn/data_parallel/test_fsdp_freezing_weights.py
- the precise condition should have been check m.parameters(), not
m.params.
- fixes #643
> [fix] better assert and better test for frozen weights

- benchmarks/experimental/sync_batchnorm.py
- fairscale/experimental/nn/__init__.py
- fairscale/experimental/nn/sync_batchnorm.py
- stubs/torch/distributed/nn/functional.pyi
- tests/ci_test_list_1.txt
- tests/experimental/nn/test_sync_batchnorm.py
Fast/simple re-implementation of SyncBatchNorm.
When profiling SSL Vision, I was seeing a majority of cycles spent in
SyncBatchNorm. With this change, I see a 10% to 20% speedup on the
model I was profiling.
When running benchmarks/experimental/sync_batchnorm.py on 8 x V100,
I get a 6x speedup:
<class 'torch.nn.modules.batchnorm.BatchNorm2d'>
Elapsed time is  0.08709120750427246
Elapsed time is  0.12632274627685547
Elapsed time is  0.14095258712768555
Elapsed time is  0.16529417037963867
Elapsed time is  0.1419970989227295
Elapsed time is  0.15166854858398438
Elapsed time is  0.12000870704650879
Elapsed time is  0.17534875869750977
<class 'torch.nn.modules.batchnorm.SyncBatchNorm'>
Elapsed time is  2.5087168216705322
Elapsed time is  2.497001886367798
Elapsed time is  2.5204885005950928 …
> [feat] experimental.nn.SyncBatchNorm: initial commit

- fairscale/nn/moe/top2gate.py
Workaround for https://github.com/pytorch/pytorch/issues/55579
Co-authored-by: @shruti-bh, @myleott
> [perf] nn.moe: workaround inefficiency in PyTorch's one_hot

- benchmarks/datasets/mnist.py
- benchmarks/datasets/wikitext2_data.py
- benchmarks/experimental/benchmark_dataset.py
- benchmarks/golden_configs/lm_wikitext2.py
- benchmarks/golden_configs/oss_mnist.py
- benchmarks/models/transformer_lm.py
- benchmarks/oss.py
- benchmarks/pipe.py
- Adds the same license header for all files in benchmarks/. Previously we had a different header in some files and 1 file did not have a header to begin with. 
> [chore][benchmarks] Add license file headers for all files in fairscale/benchmarks

- fairscale/nn/moe/top2gate.py
> [perf] nn.moe: replace einsum with faster equivalent code

- fairscale/experimental/nn/sync_batchnorm.py
- tests/experimental/nn/test_sync_batchnorm.py
> [perf] nn.SyncBatchNorm: use autograd function to save memory

- CHANGELOG.md
- docs/source/conf.py
- fairscale/__init__.py
> [chore] 0.3.7 release

- docs/source/api/index.rst
- docs/source/api/nn/moe.rst
- docs/source/index.rst
- fairscale/nn/moe/moe_layer.py
> [docs] add MOE to docs

- README.md
- docs/source/installation_instructions.rst
Updates README with more details and cleanup API references.
> [docs] Update README 

- .circleci/config.yml
- setup.py
> [test] fixing 1.9 nightly install

- CHANGELOG.md
- fairscale/nn/data_parallel/fully_sharded_data_parallel.py
- tests/nn/data_parallel/test_fsdp_state_dict.py
> Fix buffer dtype in ` FSDP.state_dict()` when using mixed precision

- fairscale/experimental/nn/sync_batchnorm.py
_SyncBatchNormFunction is a little complex in that it does the
full backward, including mean and var, but does not calculate
statistics in the forward path. Statistics are calculated outside
in the SyncBatchNorm nn.module.
This change does not impact functionality.
> [cleanup] clearly document how backward/forward are working

- benchmarks/datasets/wikitext2_data.py
Move away from using legacy torchtext iterators.
> [chore]Migrate away from legacy torchtext iterators

- tests/experimental/nn/test_multiprocess_pipe.py
To add coverage for fix in PR #722
> checking number parameters in distributed pipeline test

- fairscale/experimental/nn/distributed_pipeline/partition_handler.py
- tests/experimental/nn/test_multiprocess_pipe.py
removing implicit assumption on matching number of inputs and number of consumers for a partition
> fixing bug in setting dependencies in partition handler

- tests/nn/misc/test_grad_bucket.py
See https://github.com/pytorch/pytorch/pull/59671/
Signed-off-by: Edward Z. Yang <ezyang@fb.com>
> Future proof storage size test

- CHANGELOG.md
- docs/source/conf.py
- fairscale/__init__.py
Updated the changelog and version numbers for the next release. 
> [chore] 0.3.8 release

- CHANGELOG.md
- docs/source/conf.py
- fairscale/__init__.py
> [chore] 0.3.9 release

- CHANGELOG.md
- docs/source/conf.py
- fairscale/__init__.py
Make a new release for fairseq to use.
> [chore] 0.4.0 release

- .pre-commit-config.yaml
- CHANGELOG.md
- RELEASE.md
- requirements-test.txt
Some minor fixes.
- added missing action for releasing. This page has info about automate this https://github.com/marketplace/actions/automatic-releases. However, it may create release anytime a tag is pushed, not just tagging the master. More investigation is needed.
- removed hardcoding py3.7 version in precommit config.
> [minor] RELEASE.md and pre-commit

- CHANGELOG.md
Updates CHANGELOG for PRs submitted.
> [chore] Update CHANGELOG for submitted PRs

- fairscale/nn/checkpoint/checkpoint_activations.py
https://github.com/facebookresearch/fairscale/issues/771
> Add method for disabling gradient checkpointing

- tests/nn/checkpoint/test_checkpoint_activations.py
Fixes #778 .
https://github.com/facebookresearch/fairscale/issues/778#issue-988653326
> [test] Added disable_checkpointing unit test

- fairscale/nn/data_parallel/fully_sharded_data_parallel.py
> [doc]: updating FSDP example

- CHANGELOG.md
- fairscale/nn/checkpoint/checkpoint_activations.py
An error is caused by merging 2 different commits.
Also, added missing changelog entries.
> [fix] minor fixes for master branch

- CHANGELOG.md
- fairscale/nn/misc/param_bucket.py
- tests/nn/misc/test_param_bucket.py
> [OSS][bugfix] Fixing the cast and catching this case in the unit test

- CHANGELOG.md
- docs/source/conf.py
- fairscale/__init__.py
> [chore]0.4.1 release

- CHANGELOG.md
Update changelog for the memory tracker feature.
> [chore] Add log for the new experimental memory tracker feature.

- CHANGELOG.md
- fairscale/nn/data_parallel/fully_sharded_data_parallel.py
- stubs/torch/nn/parameter.pyi
- tests/ci_test_list_2.txt
- tests/nn/data_parallel/test_fsdp_shared_weights.py
This adds experimental and limited support of shared weights between FSDP wrapper.
When a weight is shared between layers, before this change, it needs to be part of a single FSDP wrapper. This means that while the weight is not being used, it might still be stored in GPU memory in full due to this limitation.
When we can separately wrap layers with shared weights, GPU memory can be saved. E.g.
```
L0 -> L1 -> L2 -> L3
L3.weight = L0.weight
```
Without this change, L0 and L3's weight are in the outer (root) FSDP and can't be sharded when L1 and L2 are computing.
With this change, L0 and L3 can be separately wrapped. Thus, allow the weight and gradient to be sharded as soon as it is done computing.
A special type of L3 kernel will be needed due to autograd execution order. An example of …
> [feat] [FSDP]: add experimental support to shared weights

- .circleci/config.yml
I am testing if the flaky test can be fixed with a newer nightly version.
> update nightly torch and test the flaky test

- CHANGELOG.md
- README.md
- docs/source/conf.py
- fairscale/__init__.py
- requirements.txt
> [chore] 0.4.2 release

- .circleci/config.yml
- README.md
- tests/nn/data_parallel/test_fsdp_overlap.py
- tests/nn/pipe/skip/test_gpipe.py
Fixes Issue [#843](https://github.com/facebookresearch/fairscale/issues/843)
Due to the hardware upgrade to T4 instances some tests with timers/thresholds were failing/flaky. I made small changes to make sure they pass consistently. Here's the list of tests.
increased timeout to 70 seconds for these tests (see `command` in `run_unittests_from_list`):
- test_multiple_forward_checkpoint[bn-model1-auto_wrap_bn-flatten-full]
modified timer settings for these tests in `tests/nn/data_parallel/test_fsdp_overlap.py`:
- test_forward_overlap[mixed-flatten-2]
- test_forward_overlap[mixed-no_flatten-2]
changed tolerance to 5e-1 from 2e-1 for these tests in `tests/nn/pipe/skip/test_gpipe.py`:
- test_1to3[never-3]
- test_1to3[never-1:2]
- test_1to3[never-2:1]
- test_1to3[never-1:1:1]
- …
> CI config changes

- CHANGELOG.md
- README.md
- docs/source/conf.py
- fairscale/__init__.py
- setup.py
> [chore] 0.4.3 release

- .pre-commit-config.yaml
Remove no-commit-to-branch hook from pre commit config.
> Remove no-commit-to-branch hook

- README.md
As specified in the title. There is some confusion for users about the supported/tested PyTorch versions.
> [chore]Update README to specify the exact PyTorch version we are testing with.

- README.md
Added PyTorch version in the What's New section in README.
> Add PyTorch version in README

- fairscale/utils/containers.py
- tests/ci_test_list_3.txt
- tests/nn/data_parallel/test_fsdp_hf_transformer_eval.py
Fixes #876  .
Yes
Not required
I don't think this is significant enough for an entry in the change log.
> Fix for Key Error that can happen in certain FSDP wrapping scenarios of Huggingface model sub-modules (issue #876)

- CHANGELOG.md
Fix the release date for 0.4.4
> [skip ci] updating date in changelog

- RELEASE.md
> [skip ci] update release.md

- fairscale/nn/data_parallel/fully_sharded_data_parallel.py
Removed the trailing Whitespace so that pre commit check can pass.
> fix trailing space issue

- CHANGELOG.md
Updated the change log for enabling reduce_scatter overlap with the rest operations in backward propagation. 
> [chore] Update the CHANGELOG to add details about the new feature that enables reduce_scatter overlap in backward propagation

- fairscale/optim/layerwise_gradient_scaler.py
- tests/optim/test_layerwise_gradient_scaler.py
Added 
- check param.grad is not None
- set environment variable from python. This enables the developer to run tests locally without manually setting the environment variable in the shell.
> small fixes to layerwise gradient scaler

- CHANGELOG.md
- README.md
> [Chore]release 0.4.5

- fairscale/experimental/nn/ssd_offload.py
- fairscale/nn/data_parallel/fully_sharded_data_parallel.py
Add logging to track FairScale FSDP adoptions internally
> [FSDP] Add FairScale FSDP adoptions logging

- fairscale/utils/testing.py
- tests/nn/data_parallel/test_fsdp_shared_weights_mevo.py
> [fix] reduce unit test memory and workaround the flakiness of the test

- fairscale/nn/data_parallel/fully_sharded_data_parallel.py
Backward assert can be confusing to debug. This helps a bit. Can be more helpful for sure in the future.
@ngoyal2707 @tmarkstrum @anj-s 
> [minor] make backward assert a bit better

- CHANGELOG.md
- fairscale/experimental/nn/mevo.py
- tests/experimental/nn/test_mevo.py
- added baseline algorithm to the reference kernel
- added MEVO version of LMCL
- added unit test to verify it is correct with respect to the reference as well as its memory usage
Fixes #864 .
> [feat] add CosFace paper's LMCL to MEVO

- fairscale/utils/testing.py
- tests/nn/data_parallel/test_fsdp.py
- tests/optim/test_layerwise_gradient_scaler.py
> [minor] skipping one more flaky test

- README.md
Our mission at Meta Open Source is to empower communities through open source, and we believe that it means building a welcoming and safe environment for all. As a part of this work, we are adding this banner in support for Ukraine during this crisis.
> docs: add GH button in support of Ukraine 

- .pre-commit-config.yaml
- CHANGELOG.md
- benchmarks/__init__.py
- benchmarks/datasets/__init__.py
- benchmarks/datasets/mnist.py
- benchmarks/datasets/wikitext2_data.py
- benchmarks/experimental/benchmark_dataset.py
- benchmarks/experimental/benchmark_mevo.py
- benchmarks/experimental/sync_batchnorm.py
- benchmarks/fsdp.py
- benchmarks/golden_configs/__init__.py
- benchmarks/golden_configs/lm_wikitext2.py
- benchmarks/golden_configs/oss_mnist.py
- benchmarks/models/__init__.py
- benchmarks/models/transformer_lm.py
- benchmarks/moe.py
- benchmarks/oss.py
- benchmarks/pipe.py
- benchmarks/utils.py
- codecov.yml
- docs/Makefile
- docs/source/conf.py
- fairscale/optim/adascale.py
- pyproject.toml
- requirements-dev.txt
Fixes an internal task T70826226.
> [chore] Fix copyright headers & fixed issue with mypy & NumPy versions in pre-commit

- CHANGELOG.md
- README.md
- pyproject.toml
This PR updated the change log  and the readme file for 0.4.6 release.
> [chore] 0.4.6 release

- fairscale/nn/data_parallel/fully_sharded_data_parallel.py
Adds features used in Fairseq Big to fairscale proper.
https://github.com/fairinternal/fairseq-py/issues/3185
> [FSDP] Upstream fairseq big changes

- setup.py
> Require py 3.7+

- .circleci/config.yml
> [chore] update nightly version

- tests/experimental/nn/test_ssd_offload.py
- tests/nn/checkpoint/test_checkpoint_activations.py
- tests/nn/data_parallel/test_fsdp_offload.py
> skip failed ssd offload tests for nightly

- fairscale/optim/adascale.py
Part of https://github.com/PyTorchLightning/pytorch-lightning/issues/12883
> Fix docstring format for `AdaScaleWrapper`

- fairscale/optim/adascale.py
It is interesting that pytest doesn't error out. It only print a warning. In this bug, since we are testing an error case, therefore, it triggered a bug in the unhook function that is not otherwise triggered.
> [minor]: fixing an exception on the error code path

- fairscale/optim/grad_scaler.py
- fairscale/utils/params.py
This reverts commit 0bcf4dae3035f57852e4a66271a9e2d2c58d2610.
> Revert "[refactor] Modified collections to collections.abc"

- fairscale/optim/grad_scaler.py
- fairscale/utils/params.py
Fixes # (issue #980 ).
- yes
- yes
> [refactor] Modified collections to collections.abc in import

- .gitignore
- CONTRIBUTING.md
Update CONTRIBUTING.md venv instructions to match .gitignore path.
Add .gitignore entries for pytest-testmon and IntelliJ IDE.
> [minor] updates to .gitignore and CONTRIBUTING.md

- .circleci/config.yml
Fixes flakey test failures due to pyenv downloading.
> [chore] fix pyenv download cache

- fairscale/utils/containers.py
- tests/utils/test_containers.py
> [minor] test split_non_tensor(<Tensor>) case

- fairscale/nn/checkpoint/checkpoint_activations.py
Alter ThreadLocal to a dataclass, named ThreadLocalCheckpointState
> [minor] ThreadLocal to ThreadLocalCheckpointState dataclass

- fairscale/experimental/wgit/pygit.py
- fairscale/experimental/wgit/repo.py
- fairscale/experimental/wgit/sha1_store.py
- tests/experimental/wgit/test_api.py
- tests/experimental/wgit/test_cli.py
- tests/experimental/wgit/test_sha1_store.py
1. Adds metadata creation per added file and independently tracks version of each separate file added. That is, now creates separate metadata files
for each file to be tracked.
2. Changes in reference tracking to accomodate the change in 1.
3. Somes changes in SHA1_store for better encapsulation.
4. Modified the tests to reflect above.
Update:
1. Added docstrings to the classes.
2. Added a recursively search for the weigit repo upto root.
3. Some refactor of the codes.
> weigit: Fixed file tracking with metadata. Changes in sha1_store for better encapsulation. Docstrings.

- .circleci/config.yml
> [chore] fix nightly download

- fairscale/experimental/__init__.py
- fairscale/experimental/wgit/__init__.py
Makes wgit available as a package from `fairscale.experimental`
> [Fix] Restructure for wgit availability as a package

- fairscale/internal/params.py
Switch Workhandle to a dataclass
> [minor] Workhandle as dataclass

- fair_dev/testing/testing.py
- tests/experimental/nn/test_multiprocess_pipe.py
> [test] disable a flaky test

- fairscale/experimental/wgit/cli.py
- fairscale/experimental/wgit/pygit.py
- fairscale/experimental/wgit/repo.py
- tests/experimental/wgit/test_api.py
- tests/experimental/wgit/test_cli.py
- tests/experimental/wgit/test_sha1_store.py
Adds the functionalities of weigit status.
1. Checks which files are being tracked by weigit.
2. Checks if there were changes or modifications in a file being tracked.
3. Prints out the states of a file -> 
```
1. clean, not tracking any file
2. modified, not added
3. modified, added, not committed`
4. clean: and tracking (changes commited)
```
Update:
Tests added for status.
> weigit status and checking for file modification and tracking 

- .gitignore
- fairscale/experimental/wgit/repo.py
- fairscale/experimental/wgit/sha1_store.py
- stubs/torch/serialization.pyi
- tests/experimental/wgit/test_api.py
- tests/experimental/wgit/test_cli.py
- tests/experimental/wgit/test_sha1_store.py
- mainly adding ability to add not only file but also state dict and tensors to SHA1_Store.
- many small cleanup as well. Better review the individual commits so that the changes are easier to see.
Still a work in progress, will tag you Riyasat when this is ready.
> [feat] Sha1 Store enhancements

- fairscale/experimental/wgit/sha1_store.py
- tests/experimental/wgit/test_sha1_store.py
This adds the function and test for sha1 store get function.
> [feat] add sha1_store get function

- fair_dev/common_paths.py
> [minor] copyright header

- fairscale/experimental/wgit/__init__.py
- fairscale/experimental/wgit/sha1_store.py
- requirements-dev.txt
- tests/experimental/wgit/test_sha1_store.py
This adds compression support for sha1 store so that when tensors with a lot of zeros are added, space is saved.
> [feat] add compression and tests to sha1 store

- fair_dev/testing/testing.py
- fairscale/experimental/wgit/repo.py
- fairscale/experimental/wgit/sha1_store.py
- stubs/torch/testing/__init__.pyi
- tests/experimental/wgit/test_api.py
- tests/experimental/wgit/test_cli.py
- tests/experimental/wgit/test_sha1_store.py
* this PR adds per-tensor add feature to the repo
* it also did some refactoring
* it is better to review each commit one by one in the order they were made
* each of the commit were passing all the unit tests locally.
> [feat]: add per-tensor add to repo

- fairscale/experimental/wgit/cli.py
- fairscale/experimental/wgit/repo.py
- fairscale/experimental/wgit/sha1_store.py
- tests/experimental/wgit/test_api.py
- tests/experimental/wgit/test_cli.py
Fixed a bug in original size.
Also flipped per_tensor default from False to True and exposed this via CLI.
> [fix] original size computation

- fairscale/nn/data_parallel/fully_sharded_data_parallel.py
This will be useful for checking user errors.
> [minor] add a checking around local_state_dict

- fairscale/experimental/__init__.py
> [fix]: experimental import fix

- fairscale/nn/data_parallel/fully_sharded_data_parallel.py
Fixing an issue related to fp16 data2vec training.
> [fix] handle EMA in the state_dict

- .circleci/config.yml
I noticed that pytorch 1.12 has been release. So, updating our testing versions here.
> [chore] update pytorch versions

- .circleci/config.yml
- fairscale/experimental/__init__.py
- requirements.txt
> [test] setup.py dependency testing

- fairscale/experimental/wgit/repo.py
- fairscale/experimental/wgit/signal_sparsity.py
- tests/experimental/wgit/test_signal_sparsity.py
1. implements lossy_compress with tests
2. Also adds copying of checkpoint within the repo_class
> implementation of lossy_compression method

- tests/experimental/nn/test_ssd_offload.py
- tests/experimental/nn/test_sync_batchnorm.py
- tests/nn/data_parallel/test_fsdp_memory.py
- tests/nn/data_parallel/test_fsdp_regnet.py
- tests/optim/test_oss.py
Multiple tests broken at head, blocking submissions.
> Disable broken tests

- fairscale/experimental/wgit/__init__.py
- fairscale/experimental/wgit/signal_sparsity_profiling.py
- tests/ci_test_list_3.txt
- tests/experimental/wgit/test_signal_sparsity_profiling.py
This adds a new class for measuring potential sparsity and its unit tests.
> [feat] signal sparsity profiling class

- fairscale/experimental/wgit/signal_sparsity.py
- tests/experimental/wgit/test_signal_sparsity.py
> [feat] support optional SST and DST

- fairscale/experimental/wgit/__init__.py
- fairscale/experimental/wgit/signal_sparsity.py
- tests/experimental/wgit/test_signal_sparsity.py
> [feat] add random_sparse_mask api

- fairscale/experimental/wgit/signal_sparsity.py
- tests/experimental/wgit/test_signal_sparsity.py
minor change to avoid mis-use of the api.
> [minor] fix doc and assert and test around percent

- fairscale/nn/data_parallel/fully_sharded_data_parallel.py
- fairscale/nn/wrap/auto_wrap.py
1. added better error checking
2. added a new wrap flag to automatically half a module
> [minor] help pure fp16 FSDP init a bit

- fairscale/internal/containers.py
- tests/utils/test_containers.py
> [feat] support namedtuple in container.py

- fairscale/nn/data_parallel/fully_sharded_data_parallel.py
Without it, it has been very confusing.
> [minor] add a warning in the doc

- fairscale/nn/data_parallel/fully_sharded_data_parallel.py
- tests/nn/data_parallel/test_fsdp_optimizer_utils.py
Useful when model is wrapped in particular ways.
> [bug] fix optim state gather when there is empty FSDP instances

- fairscale/internal/parallel.py
- fairscale/internal/reduce_scatter_bucketer.py
- fairscale/nn/__init__.py
- fairscale/nn/data_parallel/__init__.py
- fairscale/nn/data_parallel/fully_sharded_data_parallel.py
- move the import into typing since it is only used for type checking
- fixes #1057
> [fix] don't import ProcessGroup eagerly

- .circleci/config.yml
> [test] disable codecov

- .circleci/config.yml
> disable code cov

- fairscale/nn/data_parallel/sharded_ddp.py
- tests/nn/data_parallel/test_sharded_ddp_features.py
- Fixes from Benjamin.
Original commit msg:
- Fixes #1041. I just had a minute or two, hoping that it's enough :)
>  [fix] SDP syncing buffers during gradient accumulation

- CHANGELOG.md
- fairscale/nn/data_parallel/fully_sharded_data_parallel.py
- tests/ci_test_list_2.txt
- tests/nn/data_parallel/test_fsdp_fwd_fwd_bwd_bwd.py
Fixes #918 
This takes over the PR #923 
> [Fix][FSDP] Don't remove post backward hooks for multiple backward fix

- tests/nn/data_parallel/test_fsdp.py
> reenable a test

- docs/requirements.txt
- requirements.txt
> fix doc build

- fairscale/nn/data_parallel/fully_sharded_data_parallel.py
> minor cleanup

- .circleci/config.yml
> [chore] Ci fix

- .circleci/config.yml
- requirements-dev.txt
- setup.py
- tests/experimental/nn/test_auto_shard.py
- tests/experimental/wgit/test_sha1_store.py
Co-authored-by: Min Xu <min.xu.public@gmail.com>
> [test] ci py 3.11 tests

- fairscale/nn/misc/flatten_params_wrapper.py
> [fix] typo in flatten_params_wrapper.py

- benchmarks/datasets/wikitext2_data.py
- benchmarks/fsdp.py
valid_dataloder -> valid_dataloader
> [fix] typo in wikitext2_data.py

- fairscale/nn/model_parallel/layers.py
Fixes typo
- [ X] Did you have fun?
- [ X] Did you read the [contributor guideline](https://github.com/facebookresearch/fairscale/blob/main/CONTRIBUTING.md)?
- yeah but forgot to change commit message
- [ X] N/A
- [ X] Did you make sure to update the docs?
- [X ] N/A
- [X ] N/A
> Fix docstring typo

- docs/source/tutorials/pipe.rst
All the examples were deleted from the repo as part of issue #712
> Update documentation to remove obsolete references

- fairscale/nn/data_parallel/fully_sharded_data_parallel.py
- fairscale/utils/reduce_scatter_bucketer.py
This PR removes an extra cat operation for `flatten_parameters=True` when no padding is needed (i.e. when the flat parameter numel is divisible by the world size).
For `flatten_parameters=True`, autograd computes a flat gradient, and we chunk the flat gradient and pad the last chunk if needed. The pad implies a copy and that the chunks are no longer contiguous.
- Existing:
- Cat the chunks before reduce-scatter
- If needs padding: 1 copy for chunk, 1 copy for cat
- If does not need padding: 1 copy for cat
- New:
- If did not need padding, skip the cat and directly reduce-scatter the flat gradient
- [Same] If needs padding: 1 copy for chunk, 1 copy for cat
- [Different] If does not need padding: 0 copies
For `flatten_parameters=False`, we preserve the existing flow for this PR. …
> Removed extra `cat` before reduce-scatter

- fairscale/nn/model_parallel/layers.py
> Assign self.norm_type to input norm_type

- fairscale/nn/model_parallel/initialize.py
Add get_context_parallel_ranks() to model_parallel/initialize.py 
> add get_cp_ranks to model_parallel initialize

- fairscale/nn/model_parallel/initialize.py
We need a timeout to react faster when one of the partitions is broken
Adds a timeout # (issue).
> Add timeout in initialize_model_parallel
