- .circleci/config.yml
- requirements-test.txt
We need PyTorch v1.5 in order to test with GradScaler.
> Use PyTorch v1.5 for circleci

- fairscale/clib/fused_adam_cuda/fused_adam_cuda.cpp
- fairscale/clib/fused_adam_cuda/fused_adam_cuda_kernel.cu
- fairscale/optim/adam.py
Removes support for non multitensor mode Adam
> [feat] remove support for non-multitensor Adam

- .circleci/config.yml
- requirements-test.txt
> [chore] run tests on PyTorch 1.6.0 and gpu tests on 1.6.0 and 1.5.1

- .codecov.yml
> [chore] enforce code coverage

- benchmarks/transformer.py
- fairscale/clib/fused_adam_cuda/fused_adam_cuda_kernel.cu
- fairscale/optim/adam.py
- tests/optim/test_adam.py
Add mixed precision training to Adam. Update benchmark.
> Add mixed precision

- fairscale/optim/adam.py
- tests/optim/test_adam.py
Fixes state_dict and refactors tests further
> [fix] refactor tests and fix state_dict

- fairscale/optim/oss.py
- tests/optim/test_oss.py
Fixes the state pull and push behavior to being something more easily predictable, when a state is pulled it gets moved to CPU (failsafe if this is a reasonably big model). Upon restore the `param_groups` were not restored to the proper device. It looks like there are still probable duplicates in that field though
> [fix] OSS restore state to proper device

- .isort.cfg
- fairscale/optim/oss.py
- tests/optim/test_oss.py
Some of the optimizers in apex support additional kwargs to step
such as scale.
> [fix] optim/oss: support optimizers with additional step kwargs

- fairscale/optim/oss.py
- tests/optim/test_oss.py
Sync lr before every step and before consolidate.
> [fix] optim/oss: work correctly with LRScheduler

- benchmarks/transformer.py
Set chunks to be equal to len(balance) for pipe/transformer benchmark. Will update words per second and memory usage checks in next commit (must test on CircleCI to find appropriate values)
Fixes #51 .
> [test] specify chunks for pipe/transformer benchmark

- benchmarks/oss.py
- fairscale/optim/oss.py
- tests/optim/test_oss.py
Fixes #60 .
Except for the realization that all my lint errors were due to isort and black being version-dependent in their behaviour (FFS), all good 🙃
> [fix] OSS pytorch-compliant state dict

- fairscale/optim/oss.py
- tests/optim/test_oss.py
- [-] Was this discussed/approved via a Github issue? (no need for typos, doc improvements)
- [-] Did you make sure to update the docs?
Fixes #66
> [feat] OSS: Sync all attributes

- benchmarks/oss.py
- fairscale/optim/oss.py
- tests/optim/test_oss.py
Changes the structure of the returned state dict with respect to the param_groups to make it closer to what a vanilla optimizer would return (un-shard them). Shard again when loading
> [feat] OSS flatten state dict

- docs/requirements.txt
> [fix] fix typo in requirements.txt

- .isort.cfg
- docs/source/_static/css/customize.css
- docs/source/_templates/layout.html
- docs/source/_templates/theme_variables.jinja
- docs/source/conf.py
> [docs] use PyTorch Sphinx theme

- docs/source/_templates/layout.html
- docs/source/conf.py
Also updated canonical_url to be fairscale.
Also removed unnecessary htmi_theme_path.
> [docs] comment out mmf references

- .isort.cfg
- docs/source/api/index.rst
- docs/source/index.rst
- docs/source/tutorials/index.rst
- docs/source/tutorials/pipe.rst
> [docs] add a Pipeline tutorial

- README.md
> [feat] adding a README example for OSS

- fairscale/optim/oss.py
- tests/optim/test_oss.py
Fixes #81. In short the closure keyword is *optional* for pytorch optimizer's, but OSS made it mandatory. nVidia's LARC does not support the closure keyword, so we broke down on them. This PR fixes it by checking once at runtime whether this optimizer supports the closure keyword. 
> [feat ] OSS : optional closure argument for the optimizer

- README.md
Fixes a missing import and a broken link. Related to #63 
> [bug] hotfixes to OSS Readme

- .circleci/config.yml
- fairscale/optim/oss.py
- Release the gradients for the model parameters as soon as every rank computes its update, at this point only the gradients for this rank's shard are useful. This frees 100MB of memory for a small model (rn101) & 2 ranks, no other consequence.
- (unrelated) Adjust the circleci config to use the 4 allocated GPUs, probably a more realistic usecase
> [fix] OSS: Eager gradient release - free memory

- fairscale/optim/oss.py
Fixes #115.  Previously, optimizer state sharding was causing incorrect results when used with model parallel. This resolves the issue. In order to use this with Fairseq, you'll also need to use the [version of Fairseq from the PR I opened there](https://github.com/fairinternal/fairseq-py/pull/1326).
I confirmed that zero-sharding gives the same results in the model parallel case:
```
python fairseq_train.py --task masked_lm /checkpoint/bioseq_nonsecure/model-parallel-data/tiny_sample_valid_ur50-bin  --dataset-impl fasta  --save-dir checkpoints/zero-0-mp-1    --dropout 0.1   --optimizer adam --adam-betas '(0.9, 0.98)' --weight-decay 0.01 --clip-norm 0.0   --lr 0.0005 --lr-scheduler inverse_sqrt --warmup-updates 4000 --warmup-init-lr 1e-07   --tokens-per-sample 128 --sample-break-mode none …
```
> Support optimizer state sharding for megatron

- .circleci/config.yml
- benchmarks/oss.py
A suggestion from @msbaines on another PR made me think of that, the benchmark job that we had was not using DDP so not super realistic. The fake pictures were also the same on each rank, which prevents catching some sync issues, fixing that
> [minor] OSS: bring DDP in the benchmark

- benchmarks/oss.py
Fix issues of benchmark/oss.py when trying to run it from cpu. Make two changes:
1. set device_ids to None when calling DDP as required by [PyTorch DDP](https://pytorch.org/docs/stable/generated/torch.nn.parallel.DistributedDataParallel.html?highlight=distributeddataparallel#torch.nn.parallel.DistributedDataParallel)
2. remove max_allocated_memory when cpu is in use. For cuda, if not args.cpu will be true and max_allocated_memory will still be displayed
Talked with @blefaudeux on the issue.
> cpu support for benchmarks/oss.py

- tests/nn/pipe_process/test_bugs.py
Works around https://github.com/pytorch/pytorch/issues/47161 by calling rpc.shutdown() before exiting. My theory is that the race condition occurs when an rpc thread runs during shutdown, so I assume that calling rpc.shutdown() will prevent that. Local testing seems to indicate that it works.
> Workaround sporadic crash on shutdown in test_python_autograd_function[PipelineStyle.MultiProcess]

- tests/nn/pipe_process/test_pipe.py
Fixes #215 
cc @mrshenli, not sure why Pytorch is not following PEP440 but there's probably a reason
> [fix][Pipe] fallback for Pipe tests on internal pytorch numbering

- README.md
`pip install fairscale` doesn't work with recent pip - I am not sure if it has to do with the particular pytorch version the user has installed or whether it affects everybody who has the recent versions of it. Currently I have `pip==20.3.3`.
So the new pip started building binary packages in a special isolation where it fetches all the dependencies and then builds a mini site-packages under /tmp/pip-install-xyz and then builds the package.
The failure is a long long trace, and the middle of it is what we want:
```
File "/tmp/pip-build-env-a5x2icen/overlay/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 351, in __init__                                   
if not is_ninja_available(): …
```
> [fix] solutions to recent pip's isolation failing to build from source

- fairscale/optim/oss.py
Discussed with @blefaudeux over chat. For large transformer models where grad norm is high (~5000 per device), the OSS clip norm code causes clip norm to become inf. This is because the logic is done in fp16 and 5000 ** 2 causes overflow in fp16.
The solution is to cast everything to fp32 before squaring/reducing. The return norm is also in fp32, as a result.
> Resolve issue where grad norms because inf with OSS / fp16

- fairscale/nn/data_parallel/sharded_ddp.py
- fairscale/optim/oss.py
- tests/nn/data_parallel/test_sharded_ddp.py
Properly handle all params, with or without requires_grad, HuggingFace has triggered a bug which was always there. Remove the hash table to store the strategy (a bit risky if the tensors are moved around) and replace with a simple list. Make sure that we update the strategy if a new parameter group is added
Fixes https://github.com/huggingface/transformers/issues/9156 for the multi-node case, ie: with bucketing involved, tested locally by commenting out the no-bucketing statement.
Fixes #258 
Makes sure that this case is caught by the unit test, I'm really surprised that this was not covered before, but I did check that master fails on this
If we didn't discuss your PR in Github issues there's a high chance it …
> [OSS] Getting rid of the "should bucket" hash table, just use a list + robustness related fixes

- fairscale/optim/oss.py
- tests/optim/test_oss.py
Fixes #261, also https://github.com/huggingface/transformers/issues/9156. I suspect that this was also partially to blame with the iGPT trainings
Yes 🙃 HuggingFace / ShardedDDP / AMP works, at least the dummy example shared
> [OSS] Balance the trainable params only

- .circleci/config.yml
Not very nice because one duplicated install preset, but short term fix to make sure that master is not broken, https://github.com/facebookresearch/fairscale/pull/251 will be the real deal. In short, the default pip install torch recently changed to cuda11, and our circleci presets are around cuda 10.1 (which is probably a sane decision given torch 1.5 and 1.6 compatibility). `pip install -r requirements` thus nukes pre-installed torch with a version incompatible with the available cuda, which breaks all of our gpu-related tests (unit tests silently fail, and benchmark dies with some noise).
This adds a new install profile which overrides the default pip install with the required torch 1.7 cu101 for the gpu-related tests (but not the cpu ones, since they require some mpi dark magic which …
> [fix] CircleCI vs pip hotfix

- .circleci/config.yml
The regression detection, which triggers following https://github.com/facebookresearch/fairscale/pull/276. The gist of it is that with the current config, oss+DDP is part of the regression test, while we're really interested in OSS+ShardedDDP (and the threshold is much lower for this one actually, so the current setting was not very good).
3 changes then:
- regression test oss+sharded_ddp only
- much tighter threshold (900MB vs 1100MB) which actually reflects this solution's real perf
- keep pytorch+oss/ddp+oss/sharded_dpp as free runs, I found it useful to be able to compare the 3 solutions side by side 
Sorry for the …
> [fix] Regression testing oss+sharded_ddp only

- CHANGELOG.md
- fairscale/optim/adascale.py
- tests/optim/test_single_node_adascale.py
testing: unit tests
Fixes #269.
Fixes #224.
> [feat] sync adascale from internal repo, support add_param_group

- fairscale/nn/data_parallel/sharded_ddp.py
- fairscale/optim/oss.py
- pyproject.toml
- tests/optim/test_oss.py
This PR adds support for model parallelism in OSS. I added an [example integration with Fairseq](https://github.com/fairinternal/fairseq-py/pull/1531/files#diff-6c1200391a37100c04391c1bbee841eaa87808c15fb74bde964e0bccfde668c6R77).
The key idea is to expose `filter_params_fn` which can filter out weights that are replicated on various model parallel units. See below for an example of how this can be used. I personally think `_filter_model_parallel_params_fn` should live inside the user codebase (e.g. Fairseq) since it makes assumptions about the model architecture, but I'm also happy to add it here. The megatron code is used by many downstream codebases (including Fairscale) and should therefore appropriately mark weights with a `model_parallel` attribute.
```
def …
```
> [feat] Support model parallelism in OSS

- README.md
- fairscale/optim/adascale.py
- clarify that per-GPU batch size is not increased with AdaScale.
> [docs] clarify per-GPU batch size for AdaScale

- NOTICE
- README.md
- fairscale/nn/__init__.py
- fairscale/nn/misc/__init__.py
- fairscale/nn/misc/flatten_params_wrapper.py
- fairscale/utils/testing.py
- tests/nn/misc/test_flatten_params_wrapper.py
Adds a generic Module wrapper that flattens the Module's parameters into a single contiguous Parameter. This can be useful in many places both as a convenience and to improve speed.
> Add FlattenParamsWrapper

- fairscale/nn/misc/flatten_params_wrapper.py
- fairscale/utils/testing.py
- stubs/torch/__init__.pyi
- stubs/torch/testing/__init__.pyi
- tests/nn/misc/test_flatten_params_wrapper.py
Add some types to make mypi (mostly) happy.
However, for some reason mypi doesn't like `state_dict`:
```
$ mypy --ignore-missing-imports --scripts-are-modules --pretty .
fairscale/nn/misc/flatten_params_wrapper.py:140: error: Signature of "state_dict" incompatible with supertype "Module"
def state_dict(
^
Found 1 error in 1 file (checked 98 source files)
```
Any ideas?
Also, [CI seems to complain](https://app.circleci.com/pipelines/github/facebookresearch/fairscale/1315/workflows/799993ed-c34c-4d3c-8b63-4d11814e5499/jobs/5751) about import sorting in `tests/nn/misc/test_flatten_params_wrapper.py`, although I cannot reproduce this error locally (i.e., my local `isort` is happy with the file).
> Fix lint/typing in FlattenParamsWrapper

- benchmarks/oss.py
- requirements-test.txt
Enabler for efforts like https://github.com/facebookresearch/fairscale/issues/277.
Makes it trivial to test models a little closer to SOTA, versus RN101 which previously the biggest available model
`python3 benchmarks/oss.py  --epochs 2 --optim_type oss_sharded_ddp --model vit_small_patch16_224 --batch_size 32` is all it takes to test a ViT, the compute cost difference is pretty obvious locally. Should make it easy to test follow ups from @myleott in a CV use case
> [feat][minor] Enabling ViT in OSS benchmarks

- docs/source/tutorials/pipe.rst
- [X ] Did you read the [contributor guideline](https://github.com/facebookresearch/fairscale/blob/master/CONTRIBUTING.md)?
The link at the end of the pipe [tutorial](https://fairscale.readthedocs.io/en/latest/tutorials/pipe.html) is broken. This PR removes the link and modifies the wording.
I don't think you can refer to the examples directory from the docs directory. Let me know if I missed something. I could add a link to the repo example if you prefer. None of the other tutorials have a link to examples so I figured we can stay consistent and let people refer to it as needed. 
> [docs] Remove broken link from fairscale docs.

- .circleci/config.yml
Also, we can save time by only running unittests once instead of
twice (with and without coverage).
> [cleanup] run coverage on latest PyTorch only

- fairscale/utils/testing.py
- tests/nn/data_parallel/test_sharded_ddp.py
Fixes intermittent issues with newer python versions, I could not reproduce locally. I don't think that cpu use is super important really so not loosing much
> [fix] ShardedDDP - cpu testfix - remove Gloo/CPU

- .circleci/config.yml
- benchmarks/datasets/wikitext2_data.py
- benchmarks/golden_configs/lm_wikitext2.py
- benchmarks/pipe.py
* Reenables multiprocess nn.Pipe benchmarks(backend=nccl, rpc initialization is deprecated ProcessGroupRpcBackend)
* Moves num_decoder levels from args to config dict.
* Removes flags that we are not current testing with single or multiprocess benchmarks. They were for testing MPI + AsyncPipeline style. (we should add that benchmark in a followup PR)
* General cleanup.
> [refactor] Refactor and enable multiprocess nn.Pipe benchmarks.

- fairscale/nn/pipe/async_pipe.py
- fairscale/nn/pipe/multiprocess_pipe.py
- tests/nn/pipe_process/test_pipe.py
Also, remove run-time type checks. mypy is already checking types.
However, a user could still pass the wrong types and not use
type-checking.
> [refactor] pipe: simplify balance and module checks

- .github/workflows/build_wheels.yml
- fairscale/utils/testing.py
- tests/optim/test_oss.py
This test runs on CPU, and typically never fails, on agents which are cuda enabled (it does use Gloo and device==cpu). The newer jobs which don't have cuda randomly fail on this very same test with python3.9, even if to the best of my knowledge nothing should change. This test remains active for gpu enabled agents, even if 
> [chore] disheartening switch off of a OSS cpu test

- fairscale/optim/oss.py
In a HuggingFace benchmark we're spending 15% of the step time (without dataloading) in clip grad norm.. This is a very straightforward improvement, do not rebuild the local param iterator all the time (this itself accounted for 7% of the time)
> [perf][OSS] Clip grad norm : minor obvious speedup

- benchmarks/experimental_ampnet.py
- benchmarks/pipe.py
- fairscale/nn/pipe/async_pipe.py
- fairscale/nn/pipe/multiprocess_pipe.py
- tests/nn/model_parallel/test_layers.py
- tests/nn/pipe_process/test_pipe.py
We want to limit the number of __init__ params. If pipelined_backward
is important, we'll add it back but not make it an option.
> [refactor] multiprocess_pipe: remove pipelined_backward

- fairscale/optim/oss.py
- tests/optim/test_oss.py
Fixes #364 + adds a repro case in the unit test so that this does not happen again. I learnt one thing today, Iterables in python are consumed, they're not just a linked list.. 
cc @stas00 
> [fix] Iterables are consumed and are not linked lists..

- fairscale/optim/oss.py
Just a natural extension of the params being tensor views of a bigger tensor (#300), no need to keep the non-bucketed params, I feel a little dumb but it's just much simpler and just as fast to have one single buffer per device and per rank (or faster for multi node, less latency). 
So this PR just does that, all the trainable params which belong to the same device/rank link are packed into a single tensor, like before but not bounded. There's no tradeoff really, the original parameter memory is released.
> [refactor] OSS only use flat buffers

- fairscale/nn/pipe/async_pipe.py
- fairscale/nn/pipe/async_schedule.py
- fairscale/nn/pipe/multiprocess_pipe.py
- fairscale/nn/pipe/multiprocess_pipeline.py
- tests/nn/pipe_process/test_pipe.py
- tests/nn/pipe_process/test_transparency.py
> [refactor] remove multiprocess dependency on async

- pyproject.toml
Build isolation means that pip will create an isolated build environment and only provide the packages listed in fairscale/pyproject.toml. As `torch` is liste in fairscale/pyproject.toml, pip will always download the default torch package with gpu support from pypi. This package is very large and typically not the same as the one used in the runtime environment. I think it's better to disable the build isolation feature by default and build against the torch library that fairscale is actually being used with at runtime.
See https://github.com/facebookresearch/fairscale/issues/305
> Workaround need for pip --no-build-isolation

- fairscale/nn/misc/checkpoint_activations.py
- fairscale/utils/containers.py
- stubs/torch/utils/checkpoint.pyi
- tests/nn/misc/test_checkpoint_activations.py
- tests/utils/test_containers.py
A friendlier wrapper for performing activation checkpointing.
Compared to the PyTorch version, this version:
- wraps an nn.Module, so that all subsequent calls will use checkpointing
- handles keyword arguments in the forward
- handles non-Tensor outputs from the forward
- supports offloading activations to CPU
Usage:
```python
checkpointed_module = checkpoint_wrapper(my_module, offload_to_cpu=True)
a, b = checkpointed_module(x, y=3, z=torch.Tensor([1]))
```
> Add fairscale.nn.misc.checkpoint_activations

- fairscale/optim/oss.py
Fix for an issue that Pyspeech was seeing, it looks like I broke the logic in the last updates of  #310
The unit test did not catch that because the model was symmetrical enough, tryign to find a better test 
The bug detection and fix suggestion is from Weiyi Zheng @zhengwy888
Fixes #380
> [fix] oss dict load fix

- fairscale/nn/data_parallel/sharded_ddp.py
- fairscale/optim/oss.py
- fairscale/utils/testing.py
- tests/nn/data_parallel/test_sharded_ddp.py
Too many papercuts (or full fledged bugs) slipped through recently, and I realized that the unit tests were not covering all combinations. The module can flip from train to test, be under a no_sync context, be using AMP, trainability can change on a per-parameter basis, and buckets can be used or not.
This PR adds buckets yes/no to all tests but one, including the ddp_parity test which covers most of the matrix above. It fixes a bug which went unseen on that field (not a silent bug though, as it would assert), when leaving a no_sync context and using buckets. It fixes another bug which went unseen in handling several groups while using buckets. 
Fixes https://github.com/facebookresearch/fairscale/issues/398
Makes sure that https://github.com/facebookresearch/fairscale/issues/397 does not …
> [feature] Unit test with and without buckets for all ShardedDDP unit tests

- CHANGELOG.md
- fairscale/__init__.py
Packages a host of fixes in ShardedDDP raised by better unit testing, I think that it's worth it for many users who are not tracking master but installing via pip
Fixes https://github.com/facebookresearch/fairscale/issues/395 and https://github.com/facebookresearch/fairscale/issues/397 by adding the existing fix to the pip package eventually
> [chore] v0.1.7

- CHANGELOG.md
- fairscale/optim/oss.py
- fairscale/utils/golden_testing_data.py
- tests/optim/test_ddp_adascale.py
- tests/optim/test_oss.py
- tests/optim/test_oss_adascale.py
- tests/optim/test_single_node_adascale.py
> [fix][OSS] adding an assert for empty shards + corresponding unit test

- benchmarks/datasets/wikitext2_data.py
- benchmarks/golden_configs/lm_wikitext2.py
- benchmarks/pipe.py
- [ X] Did you read the [contributor guideline](https://github.com/facebookresearch/fairscale/blob/master/CONTRIBUTING.md)?
Split the benchmark configs to separate out those required for the model construction vs running the benchmark. This allows for code reuse across different modules.
Part of the offload work which uses the model config but not the run config.
> [refactor]Split benchmarks/ configs to contain model tuning vs run configs separately.

- fairscale/nn/data_parallel/fully_sharded_data_parallel.py
Related to #446, was running into an issue with nested FSDP wrappers. We should only cast the input on the main FSDP wrapper, excluding the check on nested FSDPs.
> Add is root check to only cast to FP16 on main FSDP wrapper

- fairscale/optim/oss.py
- tests/optim/test_oss.py
If a shard is empty, do not assert out but skip the broadcasting step indeed. The prior issue was that if somebody was using "python -O" on a distributed job, this would just hang.
Now if some ranks are empty, they just don't participate in the optimization problem (not updating any tensor), that's all (they can still participate in the data parallel part), which is probably a better take.
> [fix][minor] Change empty shard handling for OSS, do not rely on asserts

- benchmarks/golden_configs/oss_mnist.py
The tests in https://github.com/facebookresearch/fairscale/pull/474 were green multiple times so I thought that it was enough, it turns out it is not (master just broke because of that). The takeaway is that using Variable queue is slower than not using it, but it enables buckets for all models which in multi-node is a fair enough compromise in my view (without buckets the speed just tanks). May be possible to get back to improving raw speed, but not a priority I think
> [fix] OSS speed ref adjusted down..

- fairscale/utils/containers.py
- tests/utils/test_containers.py
Tried FSDP auto-wrap with RNNs, on master this fails. 
```python
import os
import torch
import torch.nn as nn
from fairscale.nn import FullyShardedDataParallel
os.environ['RANK'] = str(0)
os.environ['WORLD_SIZE'] = str(1)
os.environ["MASTER_ADDR"] = "localhost"
os.environ['MASTER_PORT'] = str(1337)
torch.cuda.set_device(0)
torch.distributed.init_process_group(backend="nccl", rank=0, world_size=1)
rnn = nn.RNN(5, 5)
rnn = FullyShardedDataParallel(rnn)
x = torch.rand((5, 1, 5), dtype=torch.float)
seq_length = torch.tensor([4], dtype=torch.int)
x = nn.utils.rnn.pack_padded_sequence(x, seq_length)
x, h = rnn(x)
x, _ = nn.utils.rnn.pad_packed_sequence(x)  # breaks because PackedSequence has not been preserved
```
Adding an additional condition to the container to ensure we preserve the object …
> Fixed RNN support for containers

- fairscale/nn/data_parallel/fully_sharded_data_parallel.py
- tests/nn/data_parallel/test_fsdp.py
Add a new test (`test_mixture_of_experts_with_delay_before_free`) that includes a delay before freeing the full parameters. This uncovered a bug/corner case in MoE when combined with activation checkpointing, which was also periodically causing the regular MoE test (without a delay) to fail in #467.
The fix is to synchronize the all_gather stream and main stream before doing the free. This isn't critical for non-MoE models, because typically the all-gather stream will keep everything in sync.
> [fix] FSDP: fix MoE corner case (fixes #467)

- CHANGELOG.md
- fairscale/optim/oss.py
- fairscale/utils/testing.py
- tests/nn/data_parallel/test_sharded_ddp_features.py
- tests/nn/data_parallel/test_sharded_ddp_pytorch_parity.py
- tests/optim/test_oss.py
It's possibly just me, but pytorch grabbing a non-manageable cuda stream for all NCCL related things is a good way to trip over. Make sure that the compute streams are done before sending the buckets, ideally everything could be lined up, but this is as good as it gets for now
> [OSS] Adding a hard sync stream barrier before broadcast

- .circleci/config.yml
- README.md
- benchmarks/golden_configs/oss_mnist.py
- fairscale/utils/testing.py
- requirements.txt
- setup.cfg
- tests/nn/pipe_process/test_rpc.py
- tests/optim/test_oss.py
> [chore] update to torch v1.8.0

- fairscale/optim/utils.py
It used to be the case, top my head that's something that @joshim5 had to introduce following accuracy issues when computing the accumulated grad norm. Compute the grad norm in fp32 then cast back to the parameter type
> [utils] Compute the grad norm in fp32 no matter what

- fairscale/nn/data_parallel/sharded_ddp.py
- tests/nn/data_parallel/test_sharded_ddp_features.py
- in any case, using buckets for a world size of one, so deactivating them 
- shardedddp does not make a lot of sense for a world size of one, but consistency and reproducibility are important, it should work
- this happens to fix #509, but I think that something else is wrong in Lightning's code in that example since Autograd is never invoked (root reason why the buckets were not flushed). It does not seems consistent, a bit flaky in my trials, happy to help debug @ananthsub and @SeanNaren 
> [fix] Lightning-compat: deactivating buckets for a single rank, should not crash but not useful

- CHANGELOG.md
- fairscale/nn/data_parallel/__init__.py
- fairscale/nn/data_parallel/fully_sharded_data_parallel.py
- tests/nn/data_parallel/test_fsdp_regnet.py
- add an utility function to handle wrapping of BN
> [feat] FSDP: add auto_wrap_bn

- fairscale/nn/data_parallel/fully_sharded_data_parallel.py
When doing mixed precision training with reshard_after_forward (i.e., nested FSDP, ZeRO-3 mode), we don't need the FP16 param shard, since it will be cast back from the FP32 shard before the backward anyway. This saves a little bit of memory.
> [perf] [FSDP] micro-optimization for memory usage

- fairscale/nn/misc/__init__.py
- fairscale/nn/misc/grad_bucket.py
- fairscale/nn/misc/param_bucket.py
- fairscale/optim/oss.py
- tests/ci_test_list_2.txt
- tests/nn/misc/test_grad_bucket.py
- tests/nn/misc/test_param_bucket.py
- tests/optim/test_oss.py
Similar to the grad buckets but with a different feature set (and small enough so that I felt that it was worth a minor duplication), add a class to represent the bucketed parameters, and make it easy to compress them to fp16 and subsequently decompress. ~20% speed boost with slow interconnect, no real accuracy loss with AMP (the FW is done with fp16 parameters anyway). Useless with fairseq for instance (parameters are already fp16 to begin with)
cc @mannatsingh, a proper implementation of what talked about a couple of months back
> [feat][refactor][OSS] Param buckets + fp16 broadcasts

- fairscale/nn/data_parallel/fully_sharded_data_parallel.py
- tests/ci_test_list_2.txt
- tests/nn/data_parallel/test_fsdp.py
- tests/nn/data_parallel/test_fsdp_apply.py
- add `compute_device` so that we can use `summon_full_params` immediately after `FSDP.__init__`, even if the params are still on CPU (this also fixes #444)
- override `FSDP.apply` so that it calls `summon_full_params` first. This makes it possible to do weight inits via `model.apply(custom_weight_init_fn)` without segfaulting, and should give identical results to not using FSDP
This also required reworking `_all_buffers_to` to no longer use `apply`, since it is called from within `_lazy_init` and created some circular logic: `apply -> summon_full_params -> _lazy_init -> _all_buffers_to -> apply`.
> [fix][FSDP] fix weight init when using apply() (fixes #490 and #444)

- fairscale/nn/data_parallel/fully_sharded_data_parallel.py
This PR tries to optimally scale gradients when the world_size is big.
For example, `reduce_scatter(gradient) / world_size` might overflow and `reduce_scatter(gradient / world_size)` might underflow with world_size=1024. We might prefer instead `reduce_scatter(gradient / 32) / 32`.
See [Nvidia’s note](https://github.com/NVIDIA/apex/blob/master/apex/parallel/distributed.py#L155) about this
Testing:
After 10 updates, I see ~ consistent loss/gnorm with the main branch and this branch.
Main:
`2021-03-31 16:55:49 | INFO | train | epoch 001 | loss 16.361 | nll_loss 16.324 | moe_gate_loss 2.56751 | overflow_expert1 24.327 | overflow_expert2 53.304 | entropy_gating 1.994 | expert1_balance_top 68.159 | expert1_balance_bottom 2.701 | unused_expert1_count 0 | expert2_balance_top 54.38 | …
> [FSDP] Add gradient predivide factor to avoid overflow/underflow with large world size

- fairscale/optim/oss.py
- tests/optim/test_oss.py
Should fix https://fb.workplace.com/groups/pytorchLightning/permalink/1419090048427529/
A usecase that I did not think of was that the model could be moved to cpu() at some point, then OSS state consolidated. In that case the state consolidation would fail because NCCL only supports cuda tensors
cc @ananthsub
> [fix] OSS - enforce cuda parameters for state consolidation if NCCL backend

- fairscale/nn/data_parallel/sharded_ddp.py
- tests/nn/data_parallel/test_sharded_ddp_features.py
Fixes eval mode not being properly handled by ShardedDDP, at best it kept all the grad hooks in place, at worst it could crash when there was a trainability change which should have been ignored. Add a unit test to catch that
Closes #586 
cc @SeanNaren  @ananthsub
> [fix][ShardedDDP] Properly handle .eval() mode

- fairscale/nn/data_parallel/fully_sharded_data_parallel.py
- tests/nn/data_parallel/test_fsdp.py
- tests/nn/data_parallel/test_fsdp_optimizer_utils.py
non broadcasted params were on GPU, but the rest of the OSD was on CPU. This wastes memory and is undesirable on the client side.
Move `no_broadcast_optim_state` params to cpu before unflattening them.
- test that all OSD state on CPU
- test that no cuda memory is used
- both of these cases fail without moving the params to GPU.
> [fix] [FSDP] optim state dict should be completely on CPU

- fairscale/nn/data_parallel/fully_sharded_data_parallel.py
- fairscale/nn/wrap/auto_wrap.py
Make `_get_default_cuda_device` fall back to the current device when the input module doesn't have any parameters.
Also fix a small doc issue in auto_wrap.
> [fix] [FSDP] Make _get_default_cuda_device more robust to modules without params

- fairscale/nn/data_parallel/sharded_ddp.py
As discussed, moving as many fields to private as possible
> [chore][SDP] API audit

- fairscale/nn/data_parallel/fully_sharded_data_parallel.py
- tests/ci_test_list_1.txt
- tests/nn/data_parallel/test_fsdp_freezing_weights.py
- an assert is changed to catch this case correctly
- unit test added (based on Quentin's test code) for this case and
compare DDP and FSDP
fixes: #610
> FSDP: fixing training with freezing weights

- benchmarks/experimental/experimental_async_approaches.py
- fairscale/nn/data_parallel/fully_sharded_data_parallel.py
- If an optimizer, like `CPUAdam`, keeps state on CPU, `all_gather` will break.
- move tensor entries to cuda before `all_gather`
> [FSDP] Consolidate cpu_adam optimizer state dict

- fairscale/optim/oss.py
Remove two deprecated code paths which were not covered by unit tests. This should bring OSS code cov to 100%
> [chore] OSS - get to 100% coverage

- fairscale/nn/data_parallel/fully_sharded_data_parallel.py
- fairscale/nn/data_parallel/sharded_ddp.py
- tests/nn/data_parallel/test_sharded_ddp_features.py
Fixes https://fb.workplace.com/groups/pytorchLightning/permalink/1432835657052968/
I'm not super clear on why this happens, but the general thinking is that this was a hard guard on not loosing any gradient, and actually the user may want to do to whatever (like, but may not be all of it: no_sync()fw/bw, then .eval()).
Keep the warning so that it's somewhat visible
> [SDP][Minor] Removing an assert which does not seem always accurate

- fairscale/nn/data_parallel/fully_sharded_data_parallel.py
- tests/ci_test_list_1.txt
- tests/ci_test_list_3.txt
- tests/nn/data_parallel/test_fsdp_multiple_wrapping.py
When integrating with Lightning, found out that as model is nested in FSDP wrapper after training, and when we call `trainer.test(model)`, it failed the assertion that the root is not set. In this case, non-root has already been set. We relax this assertion in this PR. (link to discussion: https://github.com/PyTorchLightning/pytorch-lightning/pull/6152)
> [FSDP] relax checking root condition

- fairscale/nn/data_parallel/sharded_ddp.py
- fairscale/utils/parallel.py
- this function is being removed in pytorch
- we only need to call it in case we are working with older pytorch
- internal diff:   https://www.internalfb.com/diff/D27866440?entry_point=2
> [fix] check before calling _specify_ddp_gpu_num

- fairscale/nn/data_parallel/fully_sharded_data_parallel.py
- fairscale/nn/misc/checkpoint_activations.py
- fairscale/nn/misc/misc.py
- fairscale/utils/testing.py
- stubs/torch/nn/modules/module.pyi
- t.py
- tests/ci_test_list_1.txt
- tests/nn/data_parallel/test_fsdp_freezing_weights.py
- tests/nn/data_parallel/test_fsdp_multiple_forward_checkpoint.py
This PR adds support of multiple passes of a module in a forward pass and activation checkpoint on the module at the same time.
Right now, the tested cases are:
1. FSDP(ckpt(module))
2. FSDP(ckpt(module, FSDP(BN), module))
Next commit will test and enable FSDP(ckpt(), ..., ckpt()) type of cases.
The fix is to add an option to `checkpoint_wrapper` so that it can keep a counter on the checkpointed modules so that FSDP can check the counter to determine if the backward callback fired from the module is the last one in the bigger, outer backward pass.
A new API to override the pre/post gradient divide factors. It is currently used in the test to make sure numerical match with DDP.
Fixes part of  #617 .
If we didn't …
> [fix]:  let FSDP handle model with multiple forward pass and checkpoint

- CHANGELOG.md
- fairscale/nn/data_parallel/fully_sharded_data_parallel.py
- fairscale/utils/reduce_scatter_bucketer.py
- tests/ci_test_list_1.txt
- tests/nn/data_parallel/test_fsdp_memory.py
- this fixes bug #627
- added documentation to clarify the buffer's cost and speed/memory
tradeoff
- added setup/teardown calls so that the buffer is only allocated
during the backward pass, saving more memory for forward and stepping
so that they can be used for things like activations.
- added a unit test that assert the memory is in range.
Comparing with DDP:
1. buffer size scales with # of FSDP not model size
2. buffer is only allocated during backward
3. buffer is used for small tensors only to reduce overhead
4. overlapping of compute-reduction is very different
> [feat] save memory by using bucket buffer only in backward

- CHANGELOG.md
- fairscale/nn/data_parallel/fully_sharded_data_parallel.py
- tests/ci_test_list_1.txt
- tests/ci_test_list_2.txt
- tests/ci_test_list_3.txt
- tests/nn/data_parallel/test_fsdp_freezing_weights.py
- tests/nn/data_parallel/test_fsdp_multiple_forward_checkpoint.py
- there is an issue of sync_bn with checkpoint_wrapper in AMP, particularly due to checkpoint_wrapper sets `track_running_stats` to False, which interacts badly with AMP.
- add force_input_to_fp32 flag to workaround this issue
- this flag can be used to workaround sync batch norm when AMP and checkpoint is used.
- it can also be used in case a layer insist on using fp32 inputs.
- enhanced the unit test so that it covers more types of models as well as runs faster by caching the ddp results.
- also rebalance the tests a bit.
fixes #617 . (The second test in the issue does not need to be run since we have a double forward & checkpoint test that is even bigger than that test and it doesn't hit any assertions. The bigger test do have memory issues that's separate and is being debugged.) …
> [fix]: support pytorch SyncBatchNorm under AMP & checkpointing with FSDP

- tests/nn/moe/test_top2gating.py
Context: In fairseq, I was trying to write a `topngating` function and I copied this test and it sometimes passed when it shouldn't have. 
This change makes it so that we test overflow behavior every run and assert that e0 gets at most `capacity` tokens.
> [test] Force overflow in top2gating test

- fairscale/nn/data_parallel/fully_sharded_data_parallel.py
- tests/nn/data_parallel/test_fsdp_overlap.py
* make the test more robust by using a patched all_gather with an explicit delay (instead of tuning MB)
* fix bug in test where `.item()` was not properly blocking, due to parameters not being part of the graph
* fix the actual overlapping bug by introducing a new stream for freeing full parameters
> Update + fix overlapping test to use patched all_gather w/ delay

- fairscale/nn/data_parallel/fully_sharded_data_parallel.py
- we do have a use case of empty params inside a FSDP -- for the
overlapping fsdp unit test, we use it to measure timing of compute
when no params is needed for all_gather
- therefore, I updated the comment to be more correct there.
- fixes #661
> [minor] clarify a comment

- .github/PULL_REQUEST_TEMPLATE.md
Add N/A (Not Applicable) options to some of the questions in the PR template
> [chore] Updating PR template

- fairscale/experimental/nn/offload.py
Adds pragma directives to ensure that we ignore backward passes when calculating code coverage. 
Backward passes are called from C++ code which means we never really end up calling the python functions we write when overriding autograd.Function.
> [offload] Add pragma directives to ensure we ignore the backward pass functions.

- fairscale/utils/parallel.py
- stubs/torch/distributed/__init__.pyi
- this is slightly more efficient than the previous commit
for get_process_group_cached.
> [minor] use dist.group.WORLD for default process group

- CHANGELOG.md
- fairscale/nn/data_parallel/fully_sharded_data_parallel.py
- fairscale/nn/misc/flatten_params_wrapper.py
- fairscale/utils/testing.py
- tests/ci_test_list_2.txt
- tests/nn/data_parallel/test_fsdp.py
- tests/nn/data_parallel/test_fsdp_metadata.py
Completes the PR https://github.com/facebookresearch/fairscale/pull/682 of @sshleifer (*) with more meta-data to save in order to reconstruct the full weights from the sharded weights in an offline manner (without having to instantiate a FSDP model).
This PR also add an algorithm that implements the consolidation of the weights from sharded weights without having to instantiate a FSDP model nor allocate any GPU. It works for both `flatten_parameter=True` and `flatten_parameter=False`.
(*) I do not have the permissions on the repo, so I could not push on the original PR and had to create a new one.
CC: @sshleifer  @myleott @min-xu-ai 
If we didn't discuss your PR in Github issues …
> [feat] Save FSDP metadata for offline unflattening + Consolidate checkpoints

- CHANGELOG.md
- fairscale/nn/__init__.py
- fairscale/nn/data_parallel/fully_sharded_data_parallel.py
- fairscale/nn/wrap/__init__.py
- fairscale/nn/wrap/auto_wrap.py
- stubs/torch/nn/modules/module.pyi
- tests/nn/data_parallel/test_fsdp_multiple_forward_checkpoint.py
- user can use this to avoid assert if auto_wrap is used multiple times on a module
- user can traverse the modules multiple times and assign a wrapper_config
to the module and then use auto_wrap once to wrap them
fix #649
fix #585
> [fix] auto_wrap: support wrapping based on wrapper_config

- fairscale/experimental/nn/sync_batchnorm.py
- fairscale/nn/checkpoint/__init__.py
- fairscale/nn/checkpoint/checkpoint_activations.py
- fairscale/nn/checkpoint/checkpoint_utils.py
- tests/experimental/nn/test_sync_batchnorm.py
This change also ensure that we calculate running_{mean,var} correctly
when wrapped.
> [perf] SyncBatchNorm: avoid 2nd set of all_reduce when wrapped by checkpoint_wrapper

- .circleci/config.yml
- fairscale/nn/model_parallel/cross_entropy.py
- setup.py
- tests/experimental/nn/test_multiprocess_pipe.py
1. PyTorch 1.9.0 has been released and I updated .circleci/config with it (Also torch==1.9.0.dev20210415+cu101 torchvision==0.10.0.dev20210415+cu101 are no longer available)
2. PyTorch 1.9.0 stopped supporting CUDA 10.1 and I updated circleci image from `ubuntu-1604-cuda-10.1:201909-23` to `ubuntu-1604-cuda-10.2:202012-01`
3. Looks like `ubuntu-1604-cuda-10.2:202012-01` doesn't have pyenv with python 3.7 and I have to manually force-update pyenv to get pyenv with python 3.7.0
4. I had to bump `test_multiprocess_pipe.py` pytorch version check to >=1.10.0, because with 1.9.0 it will fail with "can't pickle _thread.lock objects", but they used to work with 1.9.0.dev20210415+cu101
> Update torch to 1.9.0 release

- fairscale/experimental/nn/distributed_pipeline/graph.py
Fixes a bug in MultiInputSequential where submodules parameters are not listed with parameters() method.
> use ModuleLst for submodules

- fairscale/nn/checkpoint/checkpoint_activations.py
Use `x.to('cpu', non-blocking=True)` for potential activation checkpointing speedup.
> checkpoint_activations: use non blocking cpu transfer

- fairscale/optim/adascale.py
- requirements.txt
- setup.cfg
Certain PRs (looks like forks) are running into mypy errors due to a bumped up numpy version that is being pulled in. 
* Bumped up numpy to >=1.21 as a temporary fix. We ideally don't want to have any other dependency other than PyTorch.
* Since np.append is untyped to begin with I did not see any fix other than adding an ignore. Maybe I am missing something? 
* I am still debugging how we are pulling in numpy 1.21 for PRs that are opened outside of the fairscale repo. PRs within the repo are using numpy 1.20. I tried invalidating the cache but that did not make a difference. PRs on different forks don't share a cache with the repo  according to [circleci](https://circleci.com/docs/2.0/caching/#caching-and-open-source). Maybe we want to consider that in the future.
- Make sure you had fun …
> [fix] Add the latest numpy version to requirements.txt

- fairscale/experimental/nn/distributed_pipeline/pipeline.py
- fairscale/experimental/nn/sync_batchnorm.py
- fairscale/nn/pipe/pipe.py
- fairscale/utils/__init__.py
- fairscale/utils/testing.py
- fairscale/utils/version.py
- tests/ci_test_list_2.txt
- tests/experimental/nn/test_auto_shard.py
- tests/experimental/nn/test_multiprocess_pipe.py
- tests/experimental/nn/test_offload.py
- tests/nn/checkpoint/test_checkpoint_activations.py
- tests/nn/checkpoint/test_checkpoint_activations_norm.py
- tests/nn/data_parallel/test_fsdp.py
- tests/nn/data_parallel/test_fsdp_input.py
- tests/nn/data_parallel/test_fsdp_memory.py
- tests/nn/data_parallel/test_fsdp_multiple_forward.py
- tests/nn/data_parallel/test_fsdp_multiple_forward_checkpoint.py
- tests/nn/data_parallel/test_fsdp_multiple_wrapping.py
- tests/nn/data_parallel/test_fsdp_overlap.py
- tests/nn/data_parallel/test_fsdp_regnet.py
- tests/nn/data_parallel/test_fsdp_uneven.py
- tests/nn/data_parallel/test_fsdp_with_checkpoint_wrapper.py
- tests/nn/data_parallel/test_sharded_ddp_pytorch_parity.py
- tests/nn/moe/test_moe_layer.py
- tests/nn/pipe_process/test_pipe.py
- tests/nn/pipe_process/test_rpc.py
- tests/optim/test_oss.py
- tests/utils/test_reduce_scatter_bucketer.py
- tests/utils/test_version.py
The purpose of this PR is to get rid of code like `torch.__version__.split("+")[0].split(".")[:2] < ["1", "9"]` which will produce wrong behavior when pytorch version reaches 2 digits numbers like "1.10.0".
1. `fairscale.utils.testing.torch_version` moved to `fairscale.utils.torch_version`
2. `torch_version` reimplemented with regex parsing
> Fix pytorch version check

- requirements-test.txt
- requirements.txt
Adding a numpy requirement breaks fairseq as per this [comment](https://github.com/facebookresearch/fairscale/pull/731#issuecomment-869976994). Still debugging the RC for the numpy version change that users saw. 
> [fix]Remove numpy requirement for install and add it only for tests

- fairscale/nn/data_parallel/fully_sharded_data_parallel.py
- fairscale/nn/misc/flatten_params_wrapper.py
- tests/nn/data_parallel/test_fsdp_metadata.py
- reconstructed checkpoints would not have the shared parameter. This is different behavior. than `state_dict`.
- fsdp instances with `no_broadcast_optim_state` would still have weights concatenated from all shards. This is different behavior. than `state_dict`. 
- Behavior in aforementioned cases matches state_dict + test coverage
- we store a few more strings in `FPW._shared_param_info` so that we can easily copy shared parameters to the correct path. I'm fine for this logic to be moved to `FPW.shared_param_paths` or some such.
- 
[1/Aside] `no_broadcast_optim_state` is a bad name now, since we also don't want to broacast weights for these instances. IMO, the flag should be called `is_expert_group` since there is one use case: MoE.
> Fix shared params and MoE logic

- CHANGELOG.md
- fairscale/nn/data_parallel/fsdp_optim_utils.py
- fairscale/nn/data_parallel/fully_sharded_data_parallel.py
- fairscale/nn/misc/flatten_params_wrapper.py
- tests/nn/data_parallel/test_fsdp_metadata.py
- tests/nn/data_parallel/test_fsdp_state_dict.py
- tests/nn/wrap/test_wrap.py
This is step 3 to address #697. In this PR, we update FSDP to deal with flatten and nonflatten params in a more uniform fashion. The API is unchanged and still only allow either all flatten or none flatten. But internally, FSDP keeps flatten and nonflatten params in `m.params` in an uniform way.
There is no more `m.module` pointing to a FPW or not. It is always a FPW regardless whether flatten is used. When none of the parameter is flattened, FPW is just a noop wrapper, it simply won't have any FlatParameter objects in its `self.flat_params` list.
After this change, FSDP won't care there is 0 or more flat params and it delegates most flatten related logic to FPW. It retains the sharding related logic as well as logic related to autograd hooks etc.
It was tricky to update …
> [feat]: prepare FSDP to handle multiple flatten params and fixed metadata saving for MoE

- fairscale/nn/data_parallel/fully_sharded_data_parallel.py
- tests/nn/data_parallel/test_fsdp.py
- Move final backward callback queueing to pre-backward hook of root FSDP instance,
so that it is always attached to the outer most backward call of all the modules and fired
after all inner/re-entrant backward calls are completed.
- Added flags to check final backward callback is fired when final
backward callback is required.
- If root FSDP is checkpointed and called multiple times in forward,
checkpointer counter is used to make sure final backward callback is queued 
inside the last inner backward call as well.
unit tests, without this diff, for modified test case `test_nested_all_wrapped_model`, it will fail with following errors as final backward callback is attached to the inner backward call of checkpointed module
```python
dist init r=0, world=1
Asserting FSDP instance is: …
```
> [FSDP] Move final backward callback queueing to pre-backward hook of root instance

- CHANGELOG.md
- fairscale/nn/data_parallel/fully_sharded_data_parallel.py
- fairscale/utils/testing.py
- stubs/torch/nn/parameter.pyi
- tests/ci_test_list_1.txt
- tests/nn/data_parallel/test_fsdp_grad_acc.py
- tests/nn/data_parallel/test_fsdp_no_sync.py
Ideally we can do gradient accumulation without the `no_sync` context. In this case it should do the reduce-scatter in the backward, but accumulate into the sharded gradient so that memory usage is small.
> FSDP: supporting gradient accumulation without no_sync context manager to save GPU memory

- benchmarks/experimental/experimental_async_approaches.py
Changes fairscale test to use TensorPipe backend instead of ProcessGroup backend which has been deprecated in 1.10 (https://github.com/pytorch/pytorch/issues/55615)
> Change test to use tensorpipe rpc backend

- fairscale/nn/data_parallel/fully_sharded_data_parallel.py
`wrap` from `auto_wrap` is used in the docstring example, but was missed in the imports.
```python
self.l1 = wrap(torch.nn.Linear(5, 5))
```
> Adding missing imports in docstring

- CHANGELOG.md
- fairscale/nn/data_parallel/fully_sharded_data_parallel.py
This is a bug exposed by work of #744, by pytorch 1.10 nightly.
@zhaojuanmao, you may want to pick up this fix in your branch. It happens regardless of flatten or not. It is triggered by model that does checkpointing and multiple fwd passes.
See comments in the code for more details.
- Debugging wasn't too fun since it is a lot of prints. It took hours. Wishing there is a better way.
> [fix] [FSDP] making sure we use full params for multiple backwards within an iteration

- fairscale/optim/oss.py
- tests/optim/test_oss.py
Fixes #781, which would happen if the users wrap the optimizer before the model is moved to GPU.
> [OSS] Capture default device when refreshing the params

- fairscale/nn/checkpoint/checkpoint_activations.py
- fairscale/nn/misc/flatten_params_wrapper.py
- tests/nn/checkpoint/test_checkpoint_activations.py
Before this commit, output tensors of checkpointed modules always
require grad, even if they shouldn't. This commit makes it so that
the outputs of checkpointed modules only require grad if either
the input requires grad or if the parameters require grad.
To achieve this, this commit also adds a new _unflattened_param_views
attribute to modules being flattened. This allows the checkpointing
to still access the parameters and check if gradients need to be
computed.
This enables users to use the checkpoint wrapper on modules even if no outputs require gradients. Previously, the blocker was that the backward pass will still trigger even if the module does not need gradients, causing an assertion to fail. This is because currently the checkpoint wrapper makes the output always require …
> [feat] set requires_grad of output tensors of checkpointed modules properly

- fairscale/nn/checkpoint/checkpoint_activations.py
- fairscale/nn/checkpoint/checkpoint_utils.py
- fairscale/nn/data_parallel/fully_sharded_data_parallel.py
- stubs/torch/nn/modules/module.pyi
- tests/experimental/nn/test_sync_batchnorm.py
- tests/nn/data_parallel/test_fsdp_multiple_forward_checkpoint.py
- tests/nn/data_parallel/test_fsdp_with_checkpoint_wrapper.py
Ensure gradient reduction accumulates into the unsharded gradient tensor
within a backwards pass. This matters when an FSDP module is called
multiple times within a forward pass, and reduction is _not_ deferred
using activation checkpoint forward counters, bucketing or some other
mechanism.
Fixes #780.
> [fix] FSDP intra-backwards gradient accumulation.

- fairscale/nn/data_parallel/fully_sharded_data_parallel.py
- fairscale/utils/reduce_scatter_bucketer.py
enable users to disable using all_gather_base and reduce_scatter_base with the environment variable ENABLE_NCCL_BASE_COLLECTIVES in FSDP when all_gaterh_base and reduce_scatter_base's performance is affected by high GPU memory consumption.  
> add toggler to disable the using the nccl base collectives

- docs/source/tutorials/offload_model.rst
We are using model(inputs) instead of offload_model(inputs) which is incorrect.
> [docs][fix] Update example to use offload_model

- benchmarks/oss.py
Fix main breakage temporarily by relaxing constraints of the expected throughput.
> [chore] Fix main breakage temporarily by relaxing constraints

- fairscale/experimental/nn/ssd_offload.py
- tests/ci_test_list_2.txt
- tests/experimental/nn/test_ssd_offload.py
Adds the low level SSD APIs required for representing a tensor, reading/writing to/from memory/disk. These will be used in a future PR to implement SSD offload with FSDP.
The two main concepts here are SsdTensorHandle and SsdBuffer. The SsdTensorHandle represents a tensor that can be in memory or on disk. There are APIs to enable us to set the right metadata (memory offset, file offset, file params etc.). The SsdBuffer consists of a list of SsdTensorHandles and represents all the parameters in a module (as an example). We should be able to read all tensors to and from disk as part of the SsdBuffer.
Note: This PR is a join effort between @another-pjohnson  and @anj-s .
If we didn't …
> [feature] Add the low level SSD APIs

- .circleci/config.yml
We are unable to git clone pyenv due to updated security settings as mentioned [here](https://github.blog/2021-09-01-improving-git-protocol-security-github/#git-protocol-troubleshooting). This did not fail on the feature branch so it is definitely worrisome. Perhaps I merged it into main after the Nov 2nd deadline mentioned above?
The failed test is the flaky test we have been seeing recently. Updating to the latest nightly does not seem to have helped.
> [chore] Fix broken main due to updated github URL requirements

- docs/requirements.txt
- Updates sphinx version in docs requirements file to ensure we can use `napoleon_custom_sections` which shall be needed in [this PR](https://github.com/facebookresearch/fairscale/pull/378).
> [chore] Update Sphinx version in docs requirements file

- README.md
- docs/source/installation_instructions.rst
Since merging https://github.com/conda-forge/fairscale-feedstock/pull/2, conda-forge now has fairscale-packages also with GPU support, which I think is good enough to let people know also "officially" through the installation instructions here. :)
While editing the docs, I saw that the formatting of https://github.com/facebookresearch/fairscale/blob/main/docs/source/installation_instructions.rst didn't really work (rst vs. md), so I added some cosmetic touch-ups as I went, as well as the key insight I needed to arrive at for building the GPU packages from source (things fail without setting `TORCH_CUDA_ARCH_LIST`).
> Add installation instructions through conda

- .circleci/config.yml
- benchmarks/datasets/wikitext2_data.py
- benchmarks/golden_configs/lm_wikitext2.py
- benchmarks/models/transformer_lm.py
- benchmarks/moe.py
- benchmarks/pipe.py
- benchmarks/utils.py
- pyproject.toml
This PR adds an DDP / model parallelism benchmark based on MOE layers. This includes:
* Adding an MOE layer (with Top2Gate) to the FastForwardLayer in the TransformerLM model;
* Adding a new benchmark moe.py for the MOE model;
* Extracting util functions to utils.py so that pipe.py and moe.py can share;
* Updating data_loader APIs to support sharding;
Remaining work items:
* For now, each DDP process initializes its own dataset and dataloader, hence the data file is downloaded / unzipped in each process. This can be optimized by moving dataset initialization before DDP processes start.
* For now, the test is bottlenecked by CPU instead of GPU (CPU utilization is ~130% per process / CPU core from "top" while GPU utilization is ~40% per card from "nvidia-smi"). Need to further investigate …
> [benchmarks]Add an MOE benchmark

- CHANGELOG.md
- fairscale/nn/data_parallel/fully_sharded_data_parallel.py
- In a corner case we can lose this value
- Saving it and use it in the reset function fixed it
- A trivial case probably not worth a dedicated test for now
Fixes #878 .
> [fix] [FSDP] Do not lose original reshard_after_forward

- fairscale/experimental/nn/mevo.py
- tests/experimental/nn/test_mevo.py
- During eval, we will fallback to just output projection without fusing
- added unit test to ensure the shape is correct
> [feat] support eval in mevo

- fairscale/nn/data_parallel/sharded_ddp.py
The default for the new parameter is True and thus the default behaviour is unchanged
Fixes #874 (rather implements the feature request).
Not approved to make a pull request, but I took the liberty to create the fix; if you want it you can have it!
> Added warn_on_trainable_params_changed constructor parameter to allow the user to suppress the warning on trainable parameters changed

- CHANGELOG.md
- fairscale/optim/grad_scaler.py
Fixes a bug in the ShardedGradScaler. Initially only the first tensor in the gradient was check for inf/nan. This has been modified to make sure all tensors are checked for inf/nan now.
> [Fix] - Finiteness check for all tensors

- CHANGELOG.md
- fairscale/experimental/nn/ssd_offload.py
- fairscale/nn/data_parallel/fully_sharded_data_parallel.py
- fairscale/nn/misc/flatten_params_wrapper.py
- stubs/torch/serialization.pyi
- tests/experimental/nn/test_ssd_offload.py
- tests/nn/data_parallel/test_fsdp_offload.py
This PR completes the initial changes required to support training w/ ssd_offload enabled
* Add SsdFlatParameter paralleling FlatParameter
* Removing SsdBuffer and SsdTensorHandleView as SsdFlatParameter replaces the need for both of these.
* Adding unit tests to fairscale/tests/experimental/nn/test_ssd_offload.py
* Add full training test to fairscale/tests/nn/data_parallel/test_fsdp_offload.py
- [ X] Did you have fun?
- [ X] Did you read the [contributor guideline](https://github.com/facebookresearch/fairscale/blob/main/CONTRIBUTING.md)?
- [X ] N/A
- [ X] N/A
- [X ] Did you write any new necessary tests?
- [X ] fairscale/tests/experimental/nn/test_ssd_offload.py
- [ X] fairscale/tests/nn/data_parallel/test_fsdp_offload.py
- [X ] N/A
Anyone in the …
> Enabling ssd_offload training basic tests.

- docs/source/conf.py
- tests/nn/data_parallel/test_fsdp.py
We were pointing to a stale location for the numpy build which was causing a warning but CI fails. 
The one thing I am not able to figure out is why the failure is showing up now. Now sure if CI has started to fail on doc warnings as well as explicit failures.
> [chore] Fix docs build by updating the numpy intersphinx mapping

- fairscale/nn/data_parallel/fully_sharded_data_parallel.py
Add an arg, disable_reshard_on_root, for FSDP __init__ to handle the following issue
https://github.com/facebookresearch/fairscale/issues/878
For some cases (models wrapped by autowrap), the parameters (of root modules) needs to be sharded, and reshard_after_forward should not be set to False.
"disable_reshard_on_root" is for users to choose whether to force reshard_after_forward of root modules to be False or not.
Fixes [# 878](https://github.com/facebookresearch/fairscale/issues/878).
> [FSDP] Add an arg for FSDP __init__

- fairscale/nn/wrap/auto_wrap.py
- pyproject.toml
- tests/nn/wrap/test_wrap.py
Fixes # [791](https://github.com/facebookresearch/fairscale/issues/791).
The issue is that the root/outer module sometimes is not wrapped, depending on whether there are enough params left after children are covered by recursive wrapping: https://github.com/facebookresearch/fairscale/blob/main/fairscale/nn/wrap/auto_wrap.py#L299
So I've added a new input param to `default_auto_wrap_policy` to tell us if the current module is the root, and a new flag that allows us to wrap the root regardless of number of unwrapped params (flag is enabled by default).
Adjusted test-cases to show more clearly behavior with and without the new flag when there are not enough params left for root module.
> [fix] Add option to wrap root module in auto_wrap

- tests/nn/data_parallel/test_fsdp.py
Fixes an explicit failure in a skipped test due to a typo. This is not reproducible locally.
> [chore]Fix typo in skipped test to prevent an explicit failure

- CHANGELOG.md
- fairscale/nn/data_parallel/fsdp_optim_utils.py
- fairscale/nn/data_parallel/fully_sharded_data_parallel.py
- tests/nn/data_parallel/test_fsdp.py
- tests/nn/data_parallel/test_fsdp_optimizer_utils.py
This is to enable using expert replicas in MoE models. Previously we were only able to save and load optimizer state for unshared expert state where world size=1. With this change we should be able to aggregate state from nested modules with world sizes different from the parent module.
I've made changes to aggregating optimizer state but let me know if there is something I missed.
> [fix][FSDP] Add support for saving optimizer state with expert replication 

- README.md
Here at Meta Open Source, we've been creating short-form videos to explain Meta OSS projects in the simplest terms possible called ELI5s. We have also been working on React Labs series that we would like to add to the site. We started embedding these videos into project pages as you can see in [Docusaurus home page](https://docusaurus.io/), [Recoil](https://recoiljs.org/), [Litho](https://fblitho.com/), [Jest](https://jestjs.io/), [React Native](https://reactnative.dev/),[Hydra](https://hydra.cc/), and over 20 other projects.
> Adding ELI5 video to Fairscale

- CHANGELOG.md
- fairscale/experimental/nn/ssd_offload.py
- fairscale/nn/data_parallel/fully_sharded_data_parallel.py
- fairscale/nn/misc/flatten_params_wrapper.py
- tests/experimental/nn/test_ssd_offload.py
- tests/nn/data_parallel/test_fsdp_offload.py
> [FSDP] ssd_offload fixing backward path (grad_fn) for SsdFlatParameter and SsdFlatParameterView

- .circleci/config.yml
pyenv was moving forward before this fix. Now, it is fixed to v2.2.0. v2.3.0 breaks the circleci's bashrc.
> [test] fix circleCI failure due to pyenv versions

- tests/experimental/nn/test_ssd_offload.py
- tests/nn/data_parallel/test_sharded_ddp_features.py
- tests/nn/data_parallel/test_sharded_ddp_pytorch_parity.py
- tests/optim/test_oss.py
- tests/utils/test_containers.py
This PR removes a number of false tuples, the construction `(X)` does not create a singleton tuple in python, it just resolves to `X`; the presence of false tuples in the code is misleading to readers, and can lead to difficult debugging situations. True singleton tuples can be constructed via `(X,)`; but I've just removed these because (apparently) the tests work with the singleton values.
> [minor] Remove false tuples

- fairscale/nn/data_parallel/fully_sharded_data_parallel.py
Replace `logging.warn` (deprecated in [Python 2.7, 2011](https://github.com/python/cpython/commit/04d5bc00a219860c69ea17eaa633d3ab9917409f)) with `logging.warning` (added in [Python 2.3, 2003](https://github.com/python/cpython/commit/6fa635df7aa88ae9fd8b41ae42743341316c90f7)).
* https://docs.python.org/3/library/logging.html#logging.Logger.warning
* https://github.com/python/cpython/issues/57444
* 
- [🏅] Did you have fun?
> Replace deprecated logging.warn with logging.warning

- fairscale/experimental/wgit/repo.py
- fairscale/experimental/wgit/sha1_store.py
- tests/experimental/wgit/test_api.py
- tests/experimental/wgit/test_cli.py
- tests/experimental/wgit/test_sha1_store.py
These commits add original, deduped, gzipped sizes as well as object names to the sha1 store.
Repo class will in the future use the names metadata so that we can get an idea which tensor is which.
Repo class will expose the store/file sizes at some point.
> [feat]: add size and names metadata to sha1 store

- fairscale/experimental/wgit/repo.py
- fairscale/experimental/wgit/sha1_store.py
- tests/experimental/wgit/test_sha1_store.py
Found a few issues during testing. This fixes 2.
1. tmp file unlink() does not actually delete a file due to open FD
2. too many load/store. I refactoring the handling with a context mgr, which is better with exceptions.
> [fix] unclose FD and not load/store metadata many times

- fairscale/experimental/wgit/signal_sparsity.py
- tests/experimental/wgit/test_signal_sparsity.py
1. Implements the dense_sst_to_dst and sst_dst_to_dense method.
2. Adds tests for perfect reconstruction with all top-k across different dims.
3. Adds tests for the two new methods.
> Implmentation of dense_sst_to_dst and sst_dst_to_dense

- fairscale/nn/data_parallel/__init__.py
- fairscale/nn/data_parallel/fully_sharded_data_parallel.py
- fairscale/nn/misc/__init__.py
- fairscale/nn/misc/flatten_params_wrapper.py
With this context mgr it is possible to load a state_dict for a non-root FSDP wrapped module.
> [feat] support a context for loading state_dict for FSDP

- fairscale/fair_dev/testing/golden_testing_data.py
- fairscale/optim/adascale.py
- tests/optim/test_ddp_adascale.py
- tests/optim/test_single_node_adascale.py
Add ``is_scaled_loss`` flag to support both scaled / unscaled loss Fix ``test_grad_accum`` and``test_set_num_gradients_to_accumulate``
Fixes #1062.
> Fix gradient accumulation

- .circleci/config.yml
- .github/workflows/pre-commit.yml
- .pre-commit-config.yaml
- fairscale/fair_dev/testing/golden_testing_data.py
- fairscale/optim/adascale.py
- requirements-dev.txt
- tests/nn/checkpoint/test_checkpoint_activations.py
- tests/nn/data_parallel/test_fsdp_memory.py
- tests/nn/data_parallel/test_fsdp_multiple_forward_checkpoint.py
- tests/optim/test_ddp_adascale.py
- tests/optim/test_single_node_adascale.py
Implement `_compute_intra_grad_corr_mean` and tests
This utility function can be helpful for analyzing learning behavior.
> Implement _compute_intra_grad_corr_mean for gradient computation

- stubs/torch/__init__.pyi
Just use `torch.inf`, as torch._six is gone after https://github.com/pytorch/pytorch/pull/94709
> Remove `torch._six` from `__init__.py`

- fairscale/nn/data_parallel/fully_sharded_data_parallel.py
Fixes WPS decreasing with steps, due to the FSDP handle issues.
Credits all go to @awgu @vivien-chu . Merge this into [ngoyal_changes_for_pp_fp8](https://github.com/facebookresearch/fairscale/tree/ngoyal_changes_for_pp_fp8) due to the failure observed in test_te.py when reproducing https://github.com/fairinternal/xlformers/pull/1360 w/ @jiecaoyu @jspark1105 
```
-- Process 5 terminated with the following error:
Traceback (most recent call last):
File "/home/jianyuhuang/Work/Github/pytorch/torch/multiprocessing/spawn.py", line 74, in _wrap
fn(i, *args)
File "/home/jianyuhuang/Work/Github/xlformers/tests/test_te.py", line 470, in run_demo
loss.backward()
File "/home/jianyuhuang/Work/Github/pytorch/torch/_tensor.py", line 491, in backward
torch.autograd.backward(
File …
```
> Fix fsdp+pp+te WPS decreasing issue

- fairscale/nn/data_parallel/fully_sharded_data_parallel.py
https://github.com/facebookresearch/fairscale/pull/1139 made sure that we did not accumulate no-op `_post_backward_hook()`s over multiple iterations. This PR makes sure that we do not accumulate the hook handles and call `handle.remove()` over multiple iterations.
My fault for not catching this earlier!
<details>
<summary> Before Fix (Step 45) </summary>
</details>
<details>
<summary> After Fix (Step 45) </summary>
</details>
> Cleared backward hooks to avoid accumulating over iterations

- fairscale/nn/data_parallel/fully_sharded_data_parallel.py
Post reduction hook expects `grad` object, not `grad.data` object. This causes a bug of changing `grad.data` to another type in the `_post_reduction_hook` (if needed)
> fix no shard case

- fairscale/nn/data_parallel/fully_sharded_data_parallel.py
Fix .grad=None issue when # DP group = 1 and param is not sharded.
> fix .grad=None issue when param is not sharded

- fairscale/nn/data_parallel/fully_sharded_data_parallel.py
This PR fixes the silent errors of `params_with_grad` when `param.requires_grad=False`.
Before the fix, if we have params with `requires_grad=False`, when we call `params_with_grad` method (e.g., from gradient clipping:
- the original code first checks that `p.grad is not None` is evaluated to False
- then it tries to evaluate `p.main_grad is not None`. Since p doesn't have the main_grad attribute, this line of code will error out. When the outside caller doesn't catch this exception properly, this will lead to potential bugs.
For the fix, we added `requires_grad` check before the rest of the code.
If we didn't discuss your PR in Github issues there's a high chance it will not be …
> Added requires_grad check for params_with_grad method

- fairscale/nn/data_parallel/fully_sharded_data_parallel.py
> Changed to only run reshard hook if all gradients computed

- fairscale/nn/model_parallel/initialize.py
follow up from [D55538929](https://www.internalfb.com/diff/D55538929).
update model_parallel/initialize.py to also initialize context parallel groups.
original change made in this PR: https://github.com/fairinternal/llm_inference/pull/333/files
> add context parallel group init to mp init

- fairscale/nn/data_parallel/fully_sharded_data_parallel.py
Add `cast_input` to let users bypass the fp16 casting in FSDP.
> Add cast input argument

- fairscale/nn/model_parallel/initialize.py
Restore pipeline parallel and context parallel order for backward compatibility with dependent projects in fbcode.
> sync fbcode cp pg initialize

- fairscale/nn/data_parallel/fully_sharded_data_parallel.py
- fairscale/nn/misc/flatten_params_wrapper.py
Avoid extra memory usage caused by concat(), directly allocate flattened fp32 grads and perform fp32 grad accumulation for individual parameters on specific slice within the flattened tensor.
**baseline, optimize_backward_concat=False**
```
NVTE_TORCH_COMPILE=0 NVTE_DISABLE_NVRTC=1 CRYPTOGRAPHY_OPENSSL_NO_LEGACY=1 torchrun --master_port 1024 --nproc_per_node=8 tra
in.py --dump_dir /tmp/chriscai/xldumps --model_parallel_size 4 --seq_len=8192 --gpu_check_level=-1 --steps=5 --log_all_ste
ps=True --profile_freq=10 --dump_profile_traces=True --model.n_layers=1 --reshard_after_forward=False --batch_size=128 --m
odel.efficient_attn=flash --model.attn_bias_type=causal --model.layer_ckpt=none --model=llama3_kv8 --model.sequence_parall
el=True --mem_snapshot_stop_step 5 --log_all_steps=True …
```
> [FSDPv1] Optimize memory usage for optimize_backward_concat=True

- fairscale/nn/model_parallel/initialize.py
Sync with fbcode to support more data parallel function to prepare for expert parallelism support.
Check https://www.internalfb.com/diff/D62117903 .
> Add DP related changes to prepare for EP
